Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-10, with the labels that each got.

#886 fix: DEV-3377: Region shift on resize
  e2e/codecept.conf.js
  e2e/tests/paragraphs-filter.test.js
  e2e/tests/regression-tests/image.regions-select.test.js
  e2e/tests/regression-tests/zoomed-image-displaying.test.js
  src/tags/object/Image.js
  src/utils/feature-flags.ts
Labels: fix, Confirmed

#891 fix: DEV-3341: selected=true <Choice> attribute is not supported for Taxonomy
  src/tags/control/Taxonomy.js
Labels: fix, Confirmed

#884 fix: DEV-3284: If video fails to send a request and times out, display error message that it is not supported
  src/components/VideoCanvas/VideoCanvas.tsx
  src/components/VideoCanvas/VirtualVideo.tsx
Labels: fix, Confirmed

#894 fix: DEV-3284: Cleanup video unsupported error modal on component unmount
  e2e/fragments/LabelStudio.js
  e2e/tests/helpers.js
  e2e/tests/regression-tests/video-snapshot.test.js
  src/components/Infomodal/Infomodal.js
  src/components/VideoCanvas/VideoCanvas.tsx
Labels: fix

#890 fix: DEV-3551: Fix bug when zoom on large videos corrupts regions
  src/components/VideoCanvas/VideoCanvas.tsx
  src/components/VideoCanvas/VideoConstants.ts
  src/tags/object/Video/HtxVideo.js
Labels: fix, Confirmed

#901 ci: Copy static files before running the e2e server
  .github/workflows/build.yml
Labels: ci

#895 fix: DEV-3565: Fix region meta saving behavior
  src/components/SidePanels/DetailsPanel/RegionDetails.tsx
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
  src/mixins/Normalization.js
Labels: fix

#893 fix: DEV-3550: Check if objects are ready to enable the update button
  e2e/codecept.conf.js
  e2e/helpers/Annotations.ts
  e2e/tests/required.test.js
  src/components/TopBar/Controls.js
Labels: fix, Confirmed

#905 fix: DEV-2049: Removing interpolation hides the label, but not label selection box
  src/tags/object/Video/VideoRegions.js
Labels: fix, Confirmed

#907 fix: DEV-3590: Fix meta not saved in VOT scenario
  src/components/SidePanels/DetailsPanel/RegionDetails.tsx
Labels: fix, Confirmed

#892 feat: DEV-1041: Configurable hop size in VOT
  src/components/Settings/Settings.js
  src/components/Settings/Settings.styl
  src/components/Settings/TagSettings/Types.ts
  src/components/Settings/TagSettings/VideoSettings.tsx
  src/components/Settings/TagSettings/index.ts
  src/components/Timeline/Controls.tsx
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/Types.ts
  src/stores/SettingsStore.js
  src/tags/object/Video/HtxVideo.js
Labels: feat, Confirmed

#911 fix: DEV-3550: Revert current isReady fix
  src/components/TopBar/Controls.js
Labels: fix

#903 fix: DEV-3559: Taxonomy annotations are not displayed after selection
  src/components/ImageView/ImageView.js
  src/core/TimeTraveller.js
  src/stores/Annotation/Annotation.js
  src/tags/object/Image.js
Labels: fix, Confirmed

#915 fix: DEV-3607: Add validation if stage is ready
  src/regions/RectRegion.js
Labels: fix, Confirmed

#920 fix: DEV-3564: Annotations drawn for audio region should span all channels
  e2e/examples/audio-regions.js
  src/components/Waveform/Waveform.js
  src/regions/AudioRegion.js
Labels: fix, Confirmed

#919 fix: DEV-3543: Region navigation is not working in scrolling mode
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/stores/RegionStore.js
Labels: fix, Confirmed

#918 fix: DEV-3536: Fix filtering over choices
  src/tags/control/Choice/Choice.styl
Labels: fix, Confirmed

#929 ci: deprecate set-output syntax
  .github/workflows/build.yml
  .github/workflows/git-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: ci

#931 fix: DEV-3645: Timeseries brush to end of timeline error
  src/tags/object/TimeSeries/Channel.js
Labels: fix

#925 fix: DEV-3353: Scroll fix review stream
  src/components/App/App.js
  src/components/App/App.styl
Labels: fix, Confirmed

#926 fix: DEV-3612: History state not working with hotkeys after saving unclosed polygons
  src/mixins/DrawingTool.js
  src/regions/PolygonRegion.js
  src/stores/Annotation/Annotation.js
  src/tags/control/Polygon.js
  src/tools/Polygon.js
Labels: fix, Confirmed

#932 fix: DEV-2505: 'Update' button is displayed instead of 'Cancel skip' button in label stream if user navigates to canceled task
  src/stores/Annotation/store.js
Labels: fix, Confirmed

#934 fix: DEV-3651: If region is selected pagination doesn't work
  src/components/ImageView/ImageView.js
  src/tags/object/PagedView.js
Labels: fix, Confirmed

#700 fix: DEV-2301: Fix classification type tags render on anno history change
  src/stores/Annotation/store.js
  src/tags/TagBase.js
  src/tags/control/Base.js
  src/tags/object/Base.js
Labels: fix, Confirmed
