Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-06, with the labels that each got.

#659 fix: DEV-2480: fix startOffset for empty nodes
  src/utils/selection-tools.js
Labels: fix

#661 fix: DEV-2364: Annotation history name/timestamp spacing improvement
  src/common/Space/Space.styl
  src/common/Space/Space.tsx
  src/components/CurrentEntity/AnnotationHistory.styl
  src/components/CurrentEntity/AnnotationHistory.tsx
Labels: fix

#641 fix: DEV-2199: View all audio crash fix
  src/tags/object/AudioNext/model.js
Labels: fix

#672 ci: DEV-2511: Impersonate git username and email on dispatch
  .github/workflows/sync-pr.yml
Labels: ci

#633 fix: DEV-2244: Nested choices indeterminate state
  e2e/tests/nested-choices.test.js
  src/regions/Result.js
  src/tags/control/Choice.js
  src/tags/control/Choices.js
  src/utils/feature-flags.ts
Labels: fix

#677 fix: DEV-1592: get text after granularity applied
  src/utils/selection-tools.js
Labels: fix

#642 fix: DEV-2394: Zoomed image region out of bounds
  e2e/tests/regression-tests/image-zoom-transform.test.js
  src/components/ImageTransformer/ImageTransformer.js
  src/tags/object/Image.js
  src/utils/feature-flags.ts
Labels: fix

#674 fix: DEV-2269: Wave surfer preview crash fix
  src/components/Timeline/Views/Wave/Wave.tsx
Labels: fix

#682 ci: DEV-2543: Support PR title escaping
  .github/workflows/sync-pr.yml
Labels: ci

#673 ci: DEV-2445: Set concurrency for PR Sync
  .github/workflows/sync-pr.yml
Labels: ci

#685 fix: DEV-1975: DEV-1843: Support long unbroken taxonomy line breaks
  src/components/Taxonomy/Taxonomy.module.scss
  src/components/Taxonomy/Taxonomy.tsx
  src/components/TreeStructure/TreeStructure.tsx
  src/tags/control/Taxonomy.js
Labels: fix

#688 fix: DEV-2423: Add background as a new parameter
  src/tags/control/Shortcut.js
Labels: fix

#690 fix: DEV-2577: keep keypoints the same size
  src/hooks/useRegionColor.ts
  src/regions/KeyPointRegion.js
Labels: fix

#648 ci: DEV-2482: E2E playwright
  .github/workflows/build.yml
  codecov.yml
  e2e/codecept.conf.js
  e2e/coverage-to-istanbul.js
  e2e/fragments/AtAudioView.js
  e2e/fragments/AtImageView.js
  e2e/fragments/AtRichText.js
  e2e/fragments/AtSidebar.js
  e2e/fragments/ErrorsCollector.js
  e2e/fragments/LabelStudio.js
  e2e/helpers/MouseActions.js
  e2e/jsconfig.json
  e2e/package.json
  e2e/tests/helpers.js
  e2e/tests/history.test.js
  e2e/tests/image-labels.test.js
  e2e/tests/image.gestures.test.js
  e2e/tests/image.shapes.test.js
  e2e/tests/image.test.js
  e2e/tests/image.transformer.test.js
  e2e/tests/ner-text.test.js
  e2e/tests/ner.test.js
  e2e/tests/nested.test.js
  e2e/tests/package.json
  e2e/tests/regression-tests/image.regions-select.test.js
  e2e/tests/regression-tests/multiple-same-named-tools.test.js
  e2e/tests/required.test.js
  e2e/tests/smoke.test.js
  e2e/tests/toggle-visibility.test.js
  e2e/tsconfig.json
  e2e/utils/asserts.js
  e2e/yarn.lock
  package-lock.json
  package.json
  src/env/development.js
  yarn.lock
Labels: ci

#689 feat: DEV-2431: Alt click deletes polygon points
  src/regions/PolygonPoint.js
  src/utils/feature-flags.ts
Labels: feat

#665 fix: DEV-2465: Paragraphs data is not loading to QuickView
  src/utils/utilities.ts
Labels: fix

#676 fix: DEV-2367: User is able to edit Time Series results imported as read-only
  src/tags/object/TimeSeries/Channel.js
Labels: fix

#697 fix: DEV-2303: Video regions are editable when anno history is selected
  src/tags/object/Video/Video.js
  src/tags/object/Video/VideoRegions.js
Labels: fix

#696 fix: DEV-2302: Fix annotation history when exiting View All
  src/stores/Annotation/store.js
Labels: fix

#699 fix: DEV-1714: X-axis zoom threshold
  src/components/Timeline/Views/Wave/Wave.tsx
Labels: fix

#698 fix: DEV-2510: add guard with error message for non incremental, non sequential datasets. (#1752)
  e2e/tests/timeseries.test.js
  src/tags/object/TimeSeries.js
Labels: fix

#705 fix: DEV-2592: Bounding box is flickering during region creation
  src/mixins/DrawingTool.js
Labels: fix

#707 fix: DEV-2309: don't show the delete all region button when annotation is readonly
  src/components/Entities/Entities.js
Labels: fix

#710 fix: DEV-1442: fix FF ticket number
  src/utils/feature-flags.ts
Labels: fix

#709 fix: DEV-2207: sync speed between video and audio
  src/components/VideoCanvas/VideoCanvas.tsx
  src/mixins/SyncMixin.ts
  src/tags/object/AudioNext/model.js
  src/tags/object/AudioNext/view.tsx
  src/tags/object/Video/HtxVideo.js
  src/tags/object/Video/Video.js
  src/utils/TimeSync.ts
Labels: fix

#703 fix: DEV-1833: Prop whenChoiceValue working as expected
  src/mixins/Visibility.js
Labels: fix

#704 docs: DEV-2578: examples for dynamic labels
  src/tags/control/Choices.js
  src/tags/control/Label.js
  src/tags/control/Labels/Labels.js
  src/tags/object/Audio.js
  src/tags/object/Table.js
  src/tags/object/Video/Video.js
Labels: docs

#666 fix: DEV-2497: Enable smoothing
  src/components/ImageView/ImageView.js
  src/core/settings/editorsettings.json
  src/stores/SettingsStore.js
  src/tags/object/Image.js
Labels: fix

#724 fix: DEV-1975: fix clickable area in Taxonomy
  src/components/Taxonomy/Taxonomy.tsx
Labels: fix

#717 fix: DEV-2655: Allow cmd or ctrl to create regions immediately with deselect on canvas click enabled.
  src/components/ImageView/ImageView.js
Labels: fix

#725 fix: DEV-1975: Fix margins of Taxonomy checkbox
  src/components/Taxonomy/Taxonomy.module.scss
Labels: fix

#726 fix: DEV-2655: Support both region drawing behaviours with a settings flag
  src/components/ImageView/ImageView.js
  src/components/Settings/Settings.js
  src/core/settings/editorsettings.js
  src/core/settings/editorsettings.json
  src/stores/SettingsStore.js
Labels: fix

#716 fix: DEV-2432: Allow unfinished polygons to be saved as draft
  src/mixins/DrawingTool.js
  src/tools/Polygon.js
  src/utils/feature-flags.ts
Labels: fix

#721 fix: DEV-2437: Retain history on initial load of annotation review stream
  src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  src/stores/Annotation/store.js
Labels: fix

#719 feat: DEV-2669: Create filters for authors in Paragraph Transcription
  src/common/Select/Select.styl
  src/common/Select/Select.tsx
  src/tags/object/Paragraphs.js
  src/tags/object/Paragraphs/AuthorFilter.js
  src/tags/object/Paragraphs/Model.js
  src/tags/object/Paragraphs/Paragraphs.js
  src/tags/object/Paragraphs/Paragraphs.module.scss
  src/tags/object/Paragraphs/Phrases.js
  src/tags/object/Paragraphs/index.js
  src/utils/feature-flags.ts
Labels: feat
