Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-07, with the labels that each got.

#730 fix: DEV-2777: remove lookbehind in regex for Safari
  src/tags/object/RichText/model.js
Labels: fix

#675 fix: DEV-2462: Changing label
  src/regions/AudioRegion.js
Labels: fix

#732 fix: DEV-2379: Deselect image region bbox on short click
  src/components/ImageView/ImageView.js
  src/core/settings/editorsettings.js
  src/stores/SettingsStore.js
Labels: fix

#702 fix: DEV-2365: User is able to edit choice results imported as read-only
  src/stores/Annotation/Annotation.js
  src/tags/control/Choice.js
Labels: fix

#729 fix: DEV-2763: Multiple rendered labels in regions
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/stores/RegionStore.js
Labels: fix

#731 fix: DEV-2671: Change rotate anchor of bbox
  src/assets/icons/rotate.svg
  src/components/ImageTransformer/ImageTransformer.js
  src/components/ImageTransformer/LSTransformer.js
  src/components/ImageTransformer/LSTransformerOld.js
  src/utils/feature-flags.ts
Labels: fix

#740 ci: DEV-2802: Integrate LS follow merge
  .github/workflows/sync-pr-ls.yml
  .github/workflows/sync-pr-lse.yml
Labels: ci

#718 feat: DEV-2424: Key commands taxonomy
  src/components/Taxonomy/Taxonomy.module.scss
  src/components/Taxonomy/Taxonomy.tsx
  src/components/TreeStructure/TreeStructure.tsx
Labels: feat

#735 fix: DEV-2462: Changing label (#675)
  src/regions/AudioRegion.js
Labels: fix

#738 fix: DEV-2669: align filter items and ensure visually displays selected authors correctly
  src/common/Select/Select.styl
  src/tags/object/Paragraphs/Paragraphs.module.scss
Labels: fix

#745 fix: DEV-2431: Improve delete point logic
  src/regions/PolygonRegion.js
Labels: fix

#744 fix: DEV-2655: Hold to continuous draw image view shapes show immediately
  src/components/ImageView/ImageView.js
Labels: fix

#754 fix: DEV-2696: 3point bbox tool remains selected but hidden, when user changes label configuration from Rectangle to RectangleLabels
  src/mixins/DrawingTool.js
Labels: fix

#759 ci: DEV-2483: Migrate to Playwright
  src/regions/AudioRegion.js
  src/stores/AppStore.js
Labels: ci

#758 fix: DEV-2146: Lock rect VideoRectangle
  src/tags/object/Video/VideoRegions.js
Labels: fix

#763 fix: DEV-2926: Panels can obscure underlying content
  src/components/SidePanels/SidePanels.tsx
  src/components/SidePanels/constants.ts
Labels: fix

#765 fix: DEV-2930: Fix collapsed texts for TextArea
  src/components/SidePanels/DetailsPanel/RegionDetails.styl
  src/components/SidePanels/DetailsPanel/RegionDetails.tsx
  src/env/development.js
Labels: fix

#767 fix: DEV-2922: Selection box of rectangle region remains broken after hide/ unhide action
  src/mixins/KonvaRegion.js
Labels: fix

#746 feat: DEV-2504: Image Enhancements - Zoom, Pixelate, Center
  e2e/tests/history.test.js
  src/assets/icons/index.tsx
  src/assets/icons/tools/expand-tool.svg
  src/components/ImageView/ImageView.js
  src/components/ImageView/ImageView.module.scss
  src/components/Toolbar/FlyoutMenu.js
  src/components/Toolbar/FlyoutMenu.styl
  src/components/Toolbar/Tool.js
  src/components/Toolbar/Toolbar.js
  src/tags/object/Image.js
  src/tools/Zoom.js
  src/utils/feature-flags.ts
Labels: feat

#769 fix: DEV-2365: User is able to edit choice results imported as read-only
  src/tags/control/Choice.js
Labels: fix

#774 feat: DEV-2887: Comments for annotation editor ui
  src/assets/icons/ellipsis.svg
  src/assets/icons/index.tsx
  src/assets/icons/send.svg
  src/common/Menu/Menu.styl
  src/common/TextArea/TextArea.styl
  src/common/TextArea/TextArea.tsx
  src/common/Utils/mergeRefs.ts
  src/common/Utils/useMounted.ts
  src/components/AnnotationTab/AnnotationTab.js
  src/components/AnnotationTab/CommentsSection.styl
  src/components/Comments/CommentForm.styl
  src/components/Comments/CommentForm.tsx
  src/components/Comments/CommentItem.styl
  src/components/Comments/CommentItem.tsx
  src/components/Comments/Comments.styl
  src/components/Comments/Comments.tsx
  src/components/Comments/CommentsList.tsx
  src/components/CurrentEntity/AnnotationHistory.styl
  src/components/CurrentEntity/AnnotationHistory.tsx
  src/components/SidePanels/DetailsPanel/DetailsPanel.styl
  src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  src/stores/Annotation/Annotation.js
  src/stores/AppStore.js
  src/stores/Comment/Comment.js
  src/stores/Comment/CommentStore.js
  src/utils/date.js
  src/utils/utilities.ts
Labels: feat

#787 fix: DEV-3018: Convert app store user to reference only if the incoming value is not already a reference
  src/stores/AppStore.js
Labels: fix

#781 fix: DEV-2977: Locked polygons
  src/regions/PolygonRegion.js
Labels: fix
