Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-11, with the labels that each got.

#938 fix: DEV-3647: Eraser brush not erasing stroke
  src/components/Toolbar/Tool.js
  src/regions/BrushRegion.js
  src/tools/Erase.js
Labels: fix, Confirmed

#940 fix: DEV-3661: Use correct FF for resuming unfinished polygon
  src/regions/PolygonRegion.js
Labels: fix, Confirmed

#942 fix: DEV-3636: RegionEditor input for numbers must be recast to Number as it is a String
  src/components/SidePanels/DetailsPanel/RegionEditor.tsx
Labels: fix, Confirmed

#936 fix: DEV-1284: Fix undo with Auto Detect tool
  e2e/tests/helpers.js
  e2e/tests/regression-tests/zoomed-image-displaying.test.js
  e2e/tests/smart-tools.history.test.js
  e2e/tests/unfinished-polygons.test.js
  src/components/Toolbar/Tool.js
  src/core/TimeTraveller.js
  src/stores/Annotation/Annotation.js
  src/utils/feature-flags.ts
Labels: fix, Confirmed

#935 fix: DEV-3617: Memory leaks in Taxonomy + Repeater cases
  examples/taxonomy_large/annotations/0.json
  examples/taxonomy_large/config.xml
  examples/taxonomy_large/index.js
  examples/taxonomy_large/tasks.json
  src/LabelStudio.js
  src/core/Types.js
  src/env/development.js
  src/mixins/DynamicChildrenMixin.js
  src/mixins/SharedChoiceStore/extender.js
  src/mixins/SharedChoiceStore/mixin.js
  src/mixins/SharedChoiceStore/model.js
  src/mixins/Tool.js
  src/stores/Annotation/store.js
  src/stores/AppStore.js
  src/stores/RegionStore.js
  src/tags/control/Choice.js
  src/tags/control/Taxonomy/Taxonomy.js
  src/tags/control/Taxonomy/Taxonomy.styl
  src/tags/control/index.js
  src/tags/visual/Header.js
  src/utils/feature-flags.ts
  webpack.config-builder.js
Labels: fix

#889 fix: DEV-2993: Edit and Delete options are missing for Comments section
  src/common/TextArea/TextArea.tsx
  src/components/Comments/CommentForm.tsx
  src/components/Comments/CommentFormBase.tsx
  src/components/Comments/CommentItem.styl
  src/components/Comments/CommentItem.tsx
  src/stores/Comment/Comment.js
Labels: fix, Confirmed

#950 fix: DEV-3701: Fix value updating for dynamic children
  src/mixins/DynamicChildrenMixin.js
Labels: fix

#951 fix: DEV-3704: Fix auto-annotations not being revealed
  src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#945 fix: DEV-3467: Change border color to being visible when item is selected
  src/components/TopBar/Annotations.styl
Labels: fix, Confirmed

#943 fix: DEV-3487 Align comment icons into the same columns with annotation and drafts in dropdown selector
  src/components/CurrentEntity/GroundTruth.js
  src/components/CurrentEntity/GroundTruth.styl
  src/components/TopBar/Annotations.js
  src/components/TopBar/Annotations.styl
Labels: fix

#946 feat: DEV-3595: Improve repeater tests
  e2e/tests/repeater-paginate-scroll.test.js
Labels: feat

#955 fix: DEV-3496: Multiple clicks on 'Skip' button creates multiple skipped annotations
  src/components/TopBar/Controls.js
  src/stores/AppStore.js
Labels: fix, Confirmed

#957 fix: DEV-3720: Fix large config validation
  examples/taxonomy_large_inline/annotations/0.json
  examples/taxonomy_large_inline/config.xml
  examples/taxonomy_large_inline/index.js
  examples/taxonomy_large_inline/tasks.json
  src/core/DataValidator/ConfigValidator.js
  src/env/development.js
Labels: fix

#956 fix: DEV-3224: Assign task history from outside
  src/components/TopBar/CurrentTask.js
  src/stores/AppStore.js
Labels: fix

#992 docs: DEV-2876: Update TimeSeries Tag docs page
  src/tags/object/TimeSeries.js
Labels: docs

#991 docs: DEV-2876: Update Text tag docs page
  src/tags/object/Text.js
Labels: docs

#990 docs: DEV-2876: Update Image tag docs page
  src/tags/object/Image.js
Labels: docs

#989 docs: DEV-2876: Update HyperText tag docs page
  src/tags/object/HyperText.js
Labels: docs

#998 docs: DEV-2876: Update Table tag docs page
  src/tags/object/Table.js
Labels: docs

#997 docs: DEV-2876: Update Model tag docs page
  src/tags/object/Paragraphs/Model.js
Labels: docs

#996 docs: DEV-2876: Update Taxonomy tag docs page
  src/tags/control/Taxonomy/Taxonomy.js
Labels: docs

#986 docs: DEV-2876: Update Labels tag docs page
  src/tags/control/Labels/Labels.js
Labels: docs

#985 docs: DEV-2876: Update TimeSeriesLabels tag page
  src/tags/control/TimeSeriesLabels.js
Labels: docs

#984 docs: DEV-2876: Update Shortcut tag docs page
  src/tags/control/Shortcut.js
Labels: docs

#982 docs: DEV-2876: Update Relation docs tag page
  src/tags/control/Relation.js
Labels: docs

#981 docs: DEV-2876: Update RectangleLabels tags page
  src/tags/control/RectangleLabels.js
Labels: docs

#980 docs: DEV-2876: Update Rectangle tag docs page
  src/tags/control/Rectangle.js
Labels: docs

#979 docs: DEV-2876: Update Rating docs page
  src/tags/control/Rating.js
Labels: docs

#978 docs: DEV-2876: Update Ranker docs page
  src/tags/control/Ranker.js
Labels: docs

#976 docs: DEV-2876: Update Polygon docs page
  src/tags/control/Polygon.js
Labels: docs

#975 docs: DEV-2876: Update ParagraphLabels docs page
  src/tags/control/ParagraphLabels.js
Labels: docs

#973 docs: DEV-2876: Update List docs page
  src/tags/control/List.js
Labels: docs

#972 docs: DEV-2876: Update Label docs page
  src/tags/control/Label.js
Labels: docs

#971 docs: DEV-2876: Update KeyPointLabels docs page
  src/tags/control/KeyPointLabels.js
Labels: docs

#965 docs: DEV-2876: Update Choice tag docs page
  src/tags/control/Choice.js
Labels: docs

#967 docs: DEV-2876: Update Ellipse tag docs page
  src/tags/control/Ellipse.js
Labels: docs

#968 docs: DEV-2876: Update EllipseLabels docs page
  src/tags/control/EllipseLabels.js
Labels: docs

#969 docs: DEV-2876: Update HyperTextLabels docs page
  src/tags/control/HyperTextLabels.js
Labels: docs

#988 docs: DEV-2876: Update Audio tag docs page
  src/tags/object/Audio.js
Labels: docs

#987 docs: DEV-2876: Update TextArea tags docs page
  src/tags/control/TextArea/TextArea.js
Labels: docs

#959 docs: DEV-2876: Update TextArea tag docs page
  src/tags/control/TextArea/TextArea.js
Labels: docs

#977 docs: DEV-2876: Update PolygonLabels docs page
  src/tags/control/PolygonLabels.js
Labels: docs

#974 docs: DEV-2876: Update Pairwise docs page
  src/tags/control/Pairwise.js
Labels: docs

#970 docs: DEV-2876: Update KeyPoint docs page
  src/tags/control/KeyPoint.js
Labels: docs

#962 docs: DEV-2876: Update BrushLabels tag docs page
  src/tags/control/BrushLabels.js
Labels: docs

#983 docs: DEV-2876: Update Relations tag docs page
  src/tags/control/Relations.js
Labels: docs

#933 fix: DEV-3644: Readonly regions should always be selectable
  src/components/HtxTextBox/HtxTextBox.js
  src/components/ImageView/ImageView.js
  src/components/Taxonomy/Taxonomy.module.scss
  src/components/Taxonomy/Taxonomy.tsx
  src/components/TopBar/Controls.js
  src/components/TopBar/TopBar.js
  src/components/TreeStructure/TreeStructure.tsx
  src/mixins/KonvaRegion.js
  src/mixins/Regions.js
  src/regions/BrushRegion.js
  src/regions/EllipseRegion.js
  src/regions/ImageRegion.js
  src/regions/KeyPointRegion.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/regions/TextAreaRegion.js
  src/stores/Annotation/Annotation.js
  src/tags/control/Choice.js
  src/tags/control/Choices.js
  src/tags/control/DateTime.js
  src/tags/control/Ellipse.js
  src/tags/control/EllipseLabels.js
  src/tags/control/HyperTextLabels.js
  src/tags/control/KeyPointLabels.js
  src/tags/control/Label.js
  src/tags/control/Labels/Labels.js
  src/tags/control/List.js
  src/tags/control/Number.js
  src/tags/control/ParagraphLabels.js
  src/tags/control/Polygon.js
  src/tags/control/Ranker.js
  src/tags/control/Rating.js
  src/tags/control/Rectangle.js
  src/tags/control/RectangleLabels.js
  src/tags/control/Relation.js
  src/tags/control/Shortcut.js
  src/tags/control/Taxonomy/Taxonomy.js
  src/tags/control/TextArea/TextArea.js
  src/tags/control/TimeSeriesLabels.js
  src/tags/object/Audio.js
  src/tags/object/HyperText.js
  src/tags/object/Image.js
  src/tags/object/Paragraphs/Model.js
  src/tags/object/RichText/view.js
  src/tags/object/Table.js
  src/tags/object/Text.js
  src/tags/object/TimeSeries.js
  src/tags/object/Video/VideoRegions.js
  src/tags/visual/Header.js
  src/tags/visual/Style.js
  src/tags/visual/View.js
Labels: fix

#1010 fix: DEV-3738: Editable textarea in region list
  src/tags/control/TextArea/TextArea.js
Labels: fix, Confirmed

#1006 fix: DEV-3738: Editable textarea in region list
  src/tags/control/TextArea/TextArea.js
Labels: fix

#1013 fix: DEV-3742: Toggling textrange visibility works in outliner
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
Labels: fix, Confirmed

#1009 fix: DEV-3562: Remove styles after region unselected
  src/stores/RegionStore.js
Labels: fix, Confirmed

#1014 fix: DEV-3562: Remove styles after region unselected (#1009)
  src/stores/RegionStore.js
Labels: fix

#866 fix: DEV-3350: Video object boundaries
  public/index.html
  src/components/ImageView/ImageView.js
  src/components/Settings/TagSettings/SettingsRenderer.tsx
  src/components/Settings/TagSettings/VideoSettings.tsx
  src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  src/components/SidePanels/SidePanels.tsx
  src/components/VideoCanvas/VideoCanvas.tsx
  src/components/VideoCanvas/VideoConstants.ts
  src/core/Hotkey.ts
  src/core/Tree.tsx
  src/core/feature-flags/index.ts
  src/core/settings/types.ts
  src/core/settings/videosettings.ts
  src/env/development.js
  src/tags/object/Video/HtxVideo.js
  src/tags/object/Video/Rectangle.js
  src/tags/object/Video/Rectangle.tsx
  src/tags/object/Video/TransformTools.ts
  src/tags/object/Video/VideoRegions.js
  src/tags/object/Video/tools.ts
  src/tags/object/Video/types.ts
  src/utils/feature-flags.ts
  src/utils/utilities.ts
Labels: fix, Confirmed

#1012 fix: DEV-3672: I can't reassign label to bounding box with a hotkey
  src/tags/control/Label.js
Labels: fix, Confirmed

#1005 fix: DEV-1852: Fix missing labels on video regions
  src/components/ImageView/LabelOnRegion.js
  src/tags/object/Video/Rectangle.tsx
  src/tags/object/Video/VideoRegions.js
Labels: fix, Confirmed

#954 fix: DEV-3692: Comment edited session state
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentsList.tsx
  src/stores/Comment/Comment.js
  src/stores/Comment/CommentStore.js
Labels: fix, Confirmed

#1002 fix: DEV-3693: Explore reviews module show buggs
  e2e/tests/unfinished-polygons.test.js
  src/assets/icons/index.tsx
  src/assets/icons/warning.svg
  src/components/Entity/Entity.js
  src/components/Entity/Entity.styl
  src/components/ImageView/ImageView.js
  src/components/Node/Node.styl
  src/components/Node/Node.tsx
  src/components/SidePanels/DetailsPanel/RegionDetails.styl
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/mixins/DrawingTool.js
  src/mixins/KonvaRegion.js
  src/mixins/Regions.js
  src/tools/Polygon.js
Labels: fix, Confirmed

#1028 fix: DEV-3490: Change color when user changes label
  src/mixins/HighlightMixin.js
Labels: fix, Confirmed

#1032 fix: DEV-3825: select region in the waveform is selecting outliner
  src/lib/AudioUltra/Regions/Region.ts
  src/lib/AudioUltra/Regions/Segment.ts
  src/tags/object/AudioUltra/view.tsx
Labels: fix

#1024 Fix: DEV-3748: Fix truncated timeseries rendering
  src/tags/object/TimeSeries/Channel.js
Labels: title needs formatting, Confirmed

#1025 fix: DEV-3754: Memory usage of repeater initialization causing crashes
  src/Component.js
  src/components/CurrentEntity/AnnotationHistory.tsx
  src/components/RelationsOverlay/RelationsOverlay.js
  src/core/DataValidator/ConfigValidator.js
  src/stores/Annotation/Annotation.js
  src/stores/Annotation/store.js
  src/stores/AppStore.js
  src/tags/object/PagedView.js
Labels: fix, Confirmed

#1022 fix: DEV-2706: Fix the misalignment between frame numbers
  src/components/Timeline/Seeker.tsx
  src/components/Timeline/SideControls/FramesControl.tsx
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/Views/Frames/Frames.tsx
Labels: fix, Confirmed

#1030 fix: DEV-3835: Manual editing keypoints coordinates causes data corruption
  src/components/SidePanels/DetailsPanel/RegionEditor.tsx
Labels: fix, Confirmed

#1039 fix: DEV-3867: Fix RelationsOverlay with 3391 ff on
  src/components/RelationsOverlay/RelationsOverlay.js
Labels: fix, Confirmed

#1037 chore: DEV-3855: Fix Jest tests
  .babelrc
  .github/workflows/build_bundle.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/unit_tests.yml
  images/nick-owuor-astro-nic-visuals-wDifg5xc9Z4-unsplash.jpg
  jest.config.js
  package.json
  src/components/Hint/Hint.test.js
  src/components/Hint/__snapshots__/Hint.test.js.snap
  src/core/Hotkey.ts
  src/core/Tree.tsx
  src/tags/visual/__tests__/Header.test.jsx
  tsconfig.jest.json
  yarn.lock
Labels: chore

#1046 ci: Fix Run Server condition in e2e tests
  .github/workflows/e2e_tests.yml
Labels: ci

#1042 fix: DEV-3745: unselecting all itens in history instead just the selected item
  src/stores/AppStore.js
Labels: fix, Confirmed
