Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-12, with the labels that each got.

#1043 fix: DEV-2113: Fix annotation disappear on undo
  src/core/TimeTraveller.js
Labels: fix, Confirmed

#1023 feat: DEV-3638: Numpad hotkeys enabled
  src/core/Hotkey.ts
Labels: feat, Confirmed

#1057 chore: Fix DEV-3391 feature flag and Linting for examples
  examples/audio_classification/index.js
  examples/audio_regions/index.js
  examples/datetime/index.js
  examples/dialogue_analysis/index.js
  examples/html_document/index.js
  examples/image_bbox/index.js
  examples/image_bbox_large/index.js
  examples/image_ellipses/index.js
  examples/image_keypoints/index.js
  examples/image_multilabel/index.js
  examples/image_ocr/index.js
  examples/image_polygons/index.js
  examples/image_segmentation/index.js
  examples/image_tools/index.js
  examples/named_entity/index.js
  examples/nested_choices/complicated.js
  examples/nested_choices/index.js
  examples/pairwise/index.js
  examples/phrases/index.js
  examples/references/index.js
  examples/repeater/index.js
  examples/required/index.js
  examples/rich_text_html/index.js
  examples/rich_text_plain/index.js
  examples/rich_text_plain_remote/index.js
  examples/sentiment_analysis/index.js
  examples/table/index.js
  examples/table_csv/index.js
  examples/taxonomy/index.js
  examples/taxonomy_large/index.js
  examples/taxonomy_large_inline/index.js
  examples/timeseries/index.js
  examples/timeseries_single/index.js
  examples/transcribe_audio/index.js
  examples/video/index.js
  examples/video_audio/index.js
  examples/video_bboxes/index.js
  src/core/feature-flags/flags.json
Labels: chore

#1059 fix: DEV-3901: Paragraph overflow text issue when outliner disabled
  src/components/App/App.styl
Labels: fix

#1064 fix: DEV-3901: Paragraph overflow text issue when outliner disabled (revert)
  src/components/App/App.styl
Labels: fix

#1063 feat: DEV-2723: Editable regions time in the Outliner's Details panel
  src/components/SidePanels/DetailsPanel/RegionEditor.tsx
  src/regions/AudioRegion.js
  src/regions/AudioRegion/AudioUltraRegionModel.js
Labels: feat

#1056 fix: DEV-3892: Get showSubmitButton=false to work
  src/tags/control/TextArea/TextArea.js
Labels: fix, Confirmed

#1065 fix: DEV-3759: Region changes position on scroll + zoom
  src/tags/object/Video/HtxVideo.js
  src/tags/object/Video/VideoRegions.js
Labels: fix, Confirmed

#1069 fix: DEV-3826: Toggling Audio interfaces should correctly update the view
  src/components/Timeline/Controls.tsx
  src/components/Timeline/Controls/ConfigControl.tsx
  src/components/Timeline/Types.ts
  src/lib/AudioUltra/Regions/Regions.ts
  src/lib/AudioUltra/Regions/Segment.ts
  src/lib/AudioUltra/Timeline/Timeline.ts
  src/lib/AudioUltra/Visual/Layer.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
  src/lib/AudioUltra/Waveform.ts
  src/tags/object/AudioUltra/view.tsx
Labels: fix

#1078 fix: DEV-3826: Toggling Audio interfaces should correctly update the view
  src/lib/AudioUltra/Regions/Regions.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
Labels: fix

#1094 fix: DEV-3917: Revert #1043
  src/core/TimeTraveller.js
Labels: fix

#1088 fix: DEV-3917: Revert #1043
  src/core/TimeTraveller.js
Labels: fix, Confirmed

#1100 ci: Fix e2e workflow
  .github/workflows/e2e_tests.yml
Labels: ci

#1110 fix: DEV-4043: A3 channel data support
  e2e/codecept.conf.js
  src/env/development.js
  src/regions/AudioRegion/AudioRegionModel.js
  src/regions/AudioRegion/AudioUltraRegionModel.js
  webpack.config-builder.js
Labels: fix

#1120 ci: fix pipeline
  .github/workflows/build_bundle.yml
  .github/workflows/cancel_cicd_pipeline.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/eslint.yml
  .github/workflows/unit_tests.yml
Labels: ci

#1105 fix: DEV-3734: Add interface to show task counter
  src/components/TopBar/CurrentTask.js
Labels: fix, Confirmed

#1051 fix: DEV-3646: Fix regions copying in the Outliner
  src/components/CurrentEntity/CurrentEntity.js
  src/components/SidePanels/SidePanels.tsx
  src/core/feature-flags/flags.json
  src/env/development.js
  src/hooks/useRegionsCopyPaste.ts
  src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#1055 fix: DEV-3896: Fix closed polygon undoing by hotkey
  src/tags/control/Polygon.js
Labels: fix, Confirmed
