Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-05, with the labels that each got.

#652 feat: DEV-2458: pass comment to api on skip
  src/stores/AppStore.js
Labels: feat

#653 chore: test build automation
  src/Component.js
Labels: chore

#651 fix: DEV-2351: Hypertext-security
  src/tags/object/RichText/model.js
Labels: fix
