Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-08, with the labels that each got.

#770 fix: DEV-2942: Grouping regions without a label
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/env/development.js
  src/stores/RegionStore.js
Labels: fix

#772 fix: DEV-2934: Fix Audio resizing behavior
  src/components/Timeline/Views/Wave/Wave.tsx
  src/core/feature-flags/flags.json
  src/tags/object/AudioNext/view.tsx
Labels: fix

#775 fix: DEV-2943: Fix floating panels positioning and constraints
  src/components/SidePanels/PanelBase.tsx
  src/components/SidePanels/SidePanels.tsx
  src/components/SidePanels/constants.ts
Labels: fix

#764 fix: DEV-2931: Fix hiding NER regions with new outliner
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/mixins/HighlightMixin.js
  src/mixins/Regions.js
  src/mixins/SpanText.js
Labels: fix

#766 fix: DEV-2927: Better UI for textarea inputs in the outliner
  src/env/development.js
  src/tags/control/TextArea/TextArea.styl
Labels: fix

#788 fix: DEV-3033: Fix AuthorFilter with valueType=url
  src/tags/object/Paragraphs/Paragraphs.js
Labels: fix

#771 fix: DEV-2958: Fix NER region text not displaying in Details
  src/components/SidePanels/DetailsPanel/RegionDetails.tsx
Labels: fix

#790 fix: DEV-3049: visual bug with the Zoom To flyout menu on smaller screen sizes
  src/components/Toolbar/FlyoutMenu.styl
Labels: fix

#786 fix: DEV-2971: Disable trash button
  src/common/Button/Button.styl
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
Labels: fix

#755 fix: DEV-2514: Polygon isn't finished when moved
  src/regions/PolygonRegion.js
Labels: fix

#779 fix: DEV-2949: Annotation region locking should not persist
  src/regions/Result.js
Labels: fix

#796 chore: DEV-2504: Retire the FF for the image zoom feature
  src/components/ImageView/ImageView.js
  src/tools/Zoom.js
  src/utils/feature-flags.ts
Labels: chore

#789 feat: DEV-3034: Comments with drafts
  src/components/AnnotationTab/AnnotationTab.js
  src/components/Comments/CommentForm.tsx
  src/components/Comments/Comments.tsx
  src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  src/components/TopBar/Controls.js
  src/components/TopBar/CurrentTask.js
  src/components/TopBar/CurrentTask.styl
  src/core/External.js
  src/env/development.js
  src/env/production.js
  src/stores/Annotation/store.js
  src/stores/AppStore.js
  src/stores/Comment/CommentStore.js
  src/stores/TaskStore.js
  src/utils/feature-flags.ts
Labels: feat

#798 fix: DEV-3104: Can't upload data without annotation history
  src/stores/AppStore.js
Labels: fix

#753 docs: Small fixes to some tag docs
  src/regions/BrushRegion.js
  src/tags/control/DateTime.js
  src/tags/control/Shortcut.js
  src/tags/object/RichText/model.js
  src/tags/visual/Collapse.js
Labels: docs

#800 docs: DEV-3081: Improve Repeater docs
  src/tags/visual/Repeater.js
Labels: docs

#795 fix: DEV-2970: Fix history items rendering on the canvas
  src/components/App/App.js
  src/components/SidePanels/SidePanels.tsx
Labels: fix

#793 fix: DEV-3030: Fix paragraphs selection
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
Labels: fix

#768 feat: DEV-2671: Simplify and fix rotation calculations
  src/components/ImageTransformer/LSTransformer.js
Labels: feat

#801 fix: DEV-3110: Load draft comments correctly
  src/stores/AppStore.js
  src/stores/Comment/CommentStore.js
Labels: fix

#803 fix: DEV-3077: Repeater performance improvement
  src/components/ImageView/ImageView.js
  src/utils/feature-flags.ts
Labels: fix

#778 fix: DEV-2576: Undo keypoints when create new polygon
  src/components/ImageView/ImageView.js
  src/core/settings/keymap.json
  src/mixins/DrawingTool.js
  src/regions/PolygonRegion.js
  src/stores/AppStore.js
  src/utils/feature-flags.ts
Labels: fix

#804 fix: DEV-2978: Update automatically details panel
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
Labels: fix

#794 fix: DEV-2964: Wrap Annotation History with an interface toggle
  src/components/CurrentEntity/AnnotationHistory.tsx
  src/components/CurrentEntity/CurrentEntity.js
  src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
Labels: fix

#807 fix: DEV-3077: Add new property to turn lazyload off
  src/components/ImageView/ImageView.js
  src/tags/object/Image.js
Labels: fix

#785 fix: DEV-3004: The Zoom setting changes "Accept" to "Fix + Accept" during Review Stream
  src/components/TopBar/Controls.js
  src/tags/object/Image.js
Labels: fix

#810 fix: DEV-3073: Save prediction as draft on postpone
  src/stores/AppStore.js
Labels: fix

#811 fix: DEV-3101: Fix sving text for paragraph regions
  src/tags/object/Paragraphs/Model.js
Labels: fix

#761 feat: DEV-2755: Regions list grouped by labels with persistent & ordered collapse
  src/components/Entities/Entities.js
  src/components/Entities/Entities.module.scss
  src/components/Entities/LabelList.js
  src/stores/RegionStore.js
  src/utils/feature-flags.ts
Labels: feat

#812 fix: DEV-3211: Parse all timeseries timestamps to utc to avoid improper calculations using possible daylight savings time
  src/regions/TimeSeriesRegion.js
  src/tags/object/TimeSeries.js
  src/tags/object/TimeSeries/Channel.js
  src/tags/object/TimeSeries/helpers.js
Labels: fix

#813 fix: DEV-3140: Selecting region corrupts the history
  src/components/SidePanels/DetailsPanel/RegionEditor.styl
  src/components/SidePanels/DetailsPanel/RegionEditor.tsx
  src/components/TopBar/Actions.js
  src/env/development.js
Labels: fix

#820 ci: DEV-3253: Add chat ops git command
  .github/workflows/git-command.yml
  .github/workflows/help-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: ci

#817 fix: DEV-2968: Show/ Hide/ Lock / Unlock actions break the Undo functionality for video labels
  e2e/fragments/LabelStudio.js
  e2e/tests/helpers.js
  e2e/tests/regression-tests/video-snapshot.test.js
  public/files/opossum_intro.webm
  src/regions/VideoRegion.js
Labels: fix

#814 fix: DEV-3061: Image scaling goes lower than 1 causing small images
  src/tags/object/Image.js
Labels: fix

#821 feat: DEV-2461: Add option to sync audio with paragraphs allowing playback of chunk position
  e2e/examples/audio-paragraphs.js
  e2e/fragments/AtAudioView.js
  e2e/fragments/LabelStudio.js
  e2e/tests/audio-paragraphs.test.js
  e2e/tests/helpers.js
  e2e/tests/smoke.test.js
  src/tags/object/AudioNext/model.js
  src/tags/object/AudioNext/view.tsx
  src/tags/object/Paragraphs/Model.js
  src/tags/object/Paragraphs/Paragraphs.js
  src/utils/TimeSync.ts
  src/utils/feature-flags.ts
Labels: feat
