Repository HumanSignal/label-studio-frontend, pull requests merged in 2022-09, with the labels that each got.

#822 fix: DEV-2918: Prevent annotating collapsed phrases in paragraphs
  e2e/codecept.conf.js
  e2e/fragments/AtParagraphs.js
  e2e/helpers/Selection.js
  e2e/tests/paragraphs-filter.test.js
  src/tags/object/Paragraphs/Model.js
  src/tags/object/Paragraphs/Paragraphs.js
  src/tags/object/Paragraphs/Phrases.js
  src/utils/feature-flags.ts
  src/utils/selection-tools.js
Labels: fix, Confirmed

#818 feat: DEV-388: Introducing default attributes for AudioPlus
  src/common/Utils/useValueTracker.ts
  src/components/Timeline/SideControls/VolumeControl.tsx
  src/components/Timeline/SideControls/index.ts
  src/components/Timeline/Views/Wave/Wave.tsx
  src/components/Waveform/Waveform.js
  src/env/development.js
  src/tags/object/AudioNext/constants.ts
  src/tags/object/AudioNext/model.js
  src/tags/object/AudioNext/view.tsx
  src/tags/object/AudioNext/view_old.js
Labels: feat

#842 fix: dev-3055: Regions in 'Grouped by Label' section at Outliner tab should be ordered as they are ordered in labeling schema
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
Labels: fix, Confirmed

#844 fix: DEV-3056: User selection of regions grouping section at Outliner tab is not persistent
  src/stores/RegionStore.js
Labels: fix, Confirmed

#828 feat: DEV-3260: Introduce simplified shortcuts
  src/components/App/App.js
  src/components/Timeline/Controls.tsx
  src/core/Hotkey.ts
Labels: feat, Confirmed

#843 fix: DEV-3389: Display indices in the regions list
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/stores/RegionStore.js
Labels: fix, Confirmed

#846 fix: DEV-3402: Disable fullscreen mode
  src/tags/object/Video/HtxVideo.js
Labels: fix, Confirmed

#840 fix: DEV-3298: Repeater performance improvement
  src/common/Pagination/Pagination.styl
  src/common/Pagination/Pagination.tsx
  src/core/Tree.tsx
  src/core/settings/keymap.json
  src/tags/object/PagedView.js
  src/tags/object/index.js
  src/tags/visual/Repeater.js
  src/tags/visual/View.js
Labels: fix, Confirmed

#848 fix: DEV-3404: Allow playhead scrubbing
  src/components/Timeline/Seeker.tsx
  src/env/development.js
Labels: fix, Confirmed

#854 fix: DEV-3074: Add line between draft and annotation on annotation list
  src/components/TopBar/Annotations.js
  src/components/TopBar/Annotations.styl
Labels: fix

#856 chore: revert: DEV-3074: Add line between draft and annotation on annotation list
  src/components/TopBar/Annotations.js
  src/components/TopBar/Annotations.styl
Labels: chore

#849 fix: DEV-3403: Allow frames scrubbing
  src/components/Timeline/Views/Frames/Frames.tsx
Labels: fix, Confirmed

#845 fix: DEV-2992: Fix comments section stretching
  src/components/Comments/CommentItem.styl
Labels: fix, Confirmed

#855 fix: DEV-3429: Textarea placement in the config prevents OT
  src/tags/object/Video/HtxVideo.js
  src/tags/object/Video/Video.js
Labels: fix, Confirmed

#857 fix: DEV-3074: Add line between draft and annotation on annotation list
  src/components/TopBar/Annotations.js
  src/components/TopBar/Annotations.styl
Labels: fix, Confirmed

#858 fix: DEV-3428: Change to 1 item per page changing page by region
  src/common/Pagination/Pagination.tsx
  src/tags/object/PagedView.js
Labels: fix, Confirmed

#863 fix: DEV-2208: Don't add `labels` to textarea result
  src/regions/Result.js
  src/regions/VideoRegion.js
Labels: fix, Confirmed

#853 feat: DEV-3283: New comment behaviour for Submit/Update/Skip/Accept/Reject buttons
  src/common/TextArea/TextArea.tsx
  src/components/Comments/CommentForm.styl
  src/components/Comments/CommentForm.tsx
  src/components/TopBar/Controls.js
  src/stores/Comment/CommentStore.js
  src/utils/feature-flags.ts
Labels: feat

#860 feat: DEV-3100: Interface "postpone" for button
  src/components/TopBar/CurrentTask.js
  src/stores/AppStore.js
Labels: feat, Confirmed

#864 fix: DEV-3356: Remove `if` breaks small images zoom
  src/tags/object/Image.js
Labels: fix

#861 fix: DEV-3436: Add comment icons in annotations dropdown
  src/assets/icons/comment_check.svg
  src/assets/icons/comment_red.svg
  src/assets/icons/index.tsx
  src/components/TopBar/Annotations.js
  src/components/TopBar/Annotations.styl
  src/components/TopBar/TopBar.js
  src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#868 feat: DEV-3283: New comment behaviour for Submit/Update/Skip/Accept/Reject buttons
  src/components/Comments/CommentForm.tsx
  src/components/TopBar/Controls.js
Labels: feat, Confirmed

#852 fix: DEV-1943: After awhile, shapes disappear
  src/components/Toolbar/Tool.js
  src/core/feature-flags/flags.json
  src/mixins/DrawingTool.js
  src/regions/BrushRegion.js
  src/tags/control/KeyPoint.js
  src/tags/control/Label.js
  src/tools/Base.js
  src/tools/Brush.js
  src/tools/Ellipse.js
  src/tools/Erase.js
  src/tools/FloodFill.js
  src/tools/KeyPoint.js
  src/tools/LiveWire.js
  src/tools/Polygon.js
  src/tools/Rect.js
Labels: fix, Confirmed

#876 docs: Add docs for the video rectangle tag
  src/tags/control/VideoRectangle.js
Labels: docs

#875 fix: DEV-3502: attempting to scroll to field that doesnt exist
  src/components/TopBar/Controls.js
Labels: fix

#870 fix: DEV-3284: If video load times out display error message
  src/components/VideoCanvas/VideoCanvas.tsx
  src/hooks/useUpdateEffect.ts
Labels: fix, Confirmed

#878 Revert DEV-3284: If video load times out display error message (#870)
  src/components/VideoCanvas/VideoCanvas.tsx
  src/hooks/useUpdateEffect.ts
Labels: title needs formatting

#879 fix: DEV-3510: fix video regions w/o label
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
Labels: fix

#877 fix: DEV-3504: Retain history for Audio addRegion so init step of existing regions operates correctly
  src/components/Waveform/Waveform.js
Labels: fix, Confirmed

#882 fix: DEV-3504: Revert skip to initial audio history
  src/components/Timeline/Views/Wave/Wave.tsx
  src/components/Waveform/Waveform.js
Labels: fix

#885 fix: DEV-3304: RUNTIME ERROR occurs when user tries to change value of 'defaultZoom', 'defaultSpeed' or 'defaultVolume' attributes for '<Audio/>' tag in 'Video Timeline Segmentation' template on Safari browser
  src/components/Timeline/Views/Wave/Wave.tsx
  src/tags/object/AudioNext/view.tsx
Labels: fix, Confirmed

#883 fix: DEV-2211: Don't skip history state after Audio loads so init step of existing regions operates correctly
  src/tags/object/Audio.js
  src/tags/object/AudioNext/model.js
Labels: fix, Confirmed
