Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-04, with the labels that each got.

#1284 feat: LSDV-3025-7: Add filter that is equal or not equal as the speci…
  src/components/Filter/__tests__/filter-utils.test.tsx
  src/components/Filter/filter-util.ts
Labels: feat

#1289 feat: LSDV-3025-9: Add the remaining filters to filter component
  src/components/Filter/FilterInterfaces.tsx
  src/components/Filter/FilterRow.styl
  src/components/Filter/FilterRow.tsx
  src/components/Filter/__tests__/filter-utils.test.tsx
  src/components/Filter/filter-util.ts
Labels: feat

#1293 docs: LSDV-4901: Style and Image docs fixes
  src/tags/object/Image/Image.js
  src/tags/visual/Style.js
Labels: docs

#1295 fix: LSDV-4906: Fix classnames overlap in TopBar
  e2e/tests/regression-tests/video-snapshot.test.js
  e2e/tests/smoke.test.js
  src/components/CurrentEntity/HistoryActions.js
  src/components/CurrentEntity/HistoryActions.styl
  src/components/TopBar/HistoryActions.js
  src/components/TopBar/HistoryActions.styl
Labels: fix

#1201 fix: LSDV-3012: Syncable with new simple approach
  e2e/codecept.conf.js
  e2e/fragments/AtAudioView.js
  e2e/fragments/AtVideoView.js
  e2e/helpers/Assertion.js
  e2e/setup/feature-flags.js
  e2e/tests/audio/audio-controls.test.js
  e2e/tests/audio/audio-regions.test.js
  e2e/tests/audio/audio-webaudio-decoder.test.js
  e2e/tests/empty-labels.test.js
  e2e/tests/helpers.js
  e2e/tests/maxUsage.test.js
  e2e/tests/readonly-tests/readonly-results/audio-results-readonly.test.js
  e2e/tests/regression-tests/hotkey.test.js
  e2e/tests/smoke.test.js
  e2e/tests/sync/audio-paragraphs.test.js
  e2e/tests/sync/audio-video-paragraphs.test.js
  e2e/tests/sync/multiple-audio.test.js
  examples/audio_video_paragraphs/START.md
  examples/audio_video_paragraphs/annotations/1.json
  examples/audio_video_paragraphs/config.xml
  examples/audio_video_paragraphs/index.js
  examples/audio_video_paragraphs/tasks.json
  public/files/opossum_snow.mp4
  src/components/Timeline/Controls/ConfigControl.tsx
  src/components/VideoCanvas/VirtualVideo.tsx
  src/core/feature-flags/flags.json
  src/env/development.js
  src/lib/AudioUltra/Controls/Player.ts
  src/lib/AudioUltra/Waveform.ts
  src/lib/AudioUltra/react/index.ts
  src/mixins/Syncable.ts
  src/tags/object/AudioNext/model.js
  src/tags/object/AudioUltra/model.js
  src/tags/object/Paragraphs/HtxParagraphs.js
  src/tags/object/Paragraphs/Phrases.js
  src/tags/object/Paragraphs/__tests__/model.test.ts
  src/tags/object/Paragraphs/index.js
  src/tags/object/Paragraphs/model.js
  src/tags/object/Video/HtxVideo.js
  src/tags/object/Video/Video.js
  src/utils/feature-flags.ts
Labels: fix, breaking

#1312 test: LSDV-4943: Fix MIG Brush test
  e2e/fragments/AtImageView.js
  e2e/tests/image-list.test.js
Labels: test

#1310 feat: LSDV-3025-3: Integrate filter component into outliner
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterInterfaces.tsx
  src/components/Filter/FilterRow.tsx
  src/components/Filter/filter-util.ts
  src/components/Filter/types/Boolean.js
  src/components/Filter/types/Number.js
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/stores/RegionStore.js
Labels: feat

#1207 feat: Add a drag and drop Ranker component and tag
  examples/ranker/annotations/1.json
  examples/ranker/config.xml
  examples/ranker/index.js
  examples/ranker/tasks.json
  examples/table/config.xml
  images/screenshots/ranker.png
  package.json
  public/index.html
  src/components/Ranker/Column.tsx
  src/components/Ranker/Item.tsx
  src/components/Ranker/Ranker.module.scss
  src/components/Ranker/Ranker.tsx
  src/components/Ranker/StrictModeDroppable.tsx
  src/components/Ranker/createData.ts
  src/core/feature-flags/flags.json
  src/env/development.js
  src/regions/Result.js
  src/stores/Annotation/Annotation.js
  src/stores/RelationStore.js
  src/tags/control/index.js
  src/tags/object/Ranker.js
  src/tags/object/index.js
  src/tags/visual/View.js
  src/utils/feature-flags.ts
  yarn.lock
Labels: feat, breaking

#1313 fix: LSDV-4903: Fix Video tag null rendering
  e2e/tests/regression-tests/video-unmount.test.js
  src/components/VideoCanvas/VirtualVideo.tsx
Labels: fix

#1307 fix: LSDV-4887: Task view group bug fix
  src/components/InstructionsModal/InstructionsModal.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  src/components/SidePanels/TabPanels/PanelTabsBase.tsx
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
  src/components/SidePanels/TabPanels/Tabs.tsx
  src/components/SidePanels/TabPanels/__tests__/utils.test.tsx
  src/components/SidePanels/TabPanels/types.ts
  src/components/SidePanels/TabPanels/utils.ts
Labels: fix

#1317 fix: LSDV-4881: Fix missed points in optimized timeseries
  e2e/fragments/AtTimeSeries.js
  e2e/setup/feature-flags.js
  e2e/tests/timeseries.test.js
  src/tags/object/TimeSeries/Channel.js
  src/utils/feature-flags.ts
Labels: fix

#1294 fix: LSDV-4684: Fix check for image boundaries
  e2e/fragments/LabelStudio.js
  e2e/tests/image.test.js
  src/mixins/DrawingTool.js
Labels: fix

#1248 fix: LSDV-4757: Fix brush crashing
  src/tools/Brush.js
  src/tools/Erase.js
  src/tools/Zoom.js
Labels: fix, breaking

#1309 feat: LSDV-4712: Add effect of skipDuplicates parameter on results editing
  e2e/fragments/AtOutliner.js
  e2e/setup/feature-flags.js
  e2e/tests/textarea.skip-duplicates.test.js
  src/regions/TextAreaRegion.js
  src/tags/control/TextArea/TextArea.js
  src/utils/feature-flags.ts
Labels: feat

#1296 chore: LSDV-4727: Remove any AudioPlus mentions
  e2e/examples/audio-paragraphs.js
  e2e/examples/audio-regions.js
  e2e/tests/audio/audio-controls.test.js
  e2e/tests/audio/audio-errors.test.js
  e2e/tests/audio/audio-regions.test.js
  e2e/tests/audio/audio-webaudio-decoder.test.js
  e2e/tests/empty-labels.test.js
  e2e/tests/maxUsage.test.js
  e2e/tests/shortcuts.test.js
  e2e/tests/smoke.test.js
  e2e/tests/sync/audio-paragraphs.test.js
  e2e/tests/sync/multiple-audio.test.js
  examples/audio_regions/config.xml
  examples/video_audio/config.xml
Labels: chore

#1322 fix: LSDV-4953: Filter cut off at default panel width
  src/components/SidePanels/OutlinerPanel/ViewControls.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
Labels: fix

#1273 fix: LSDV-4836: Conditional annotation with visibleWhen choice-selected works with Taxonomy
  e2e/tests/taxonomy.test.js
  src/mixins/SelectedChoiceMixin.js
  src/mixins/Visibility.js
  src/regions/Result.js
  src/tags/control/Choices.js
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix

#1299 fix: LSDV-4711: CORS error accessing previously annotated data
  src/components/ImageView/Image.js
  src/components/ImageView/ImageView.js
  src/components/VideoCanvas/VideoCanvas.tsx
  src/components/VideoCanvas/VirtualVideo.tsx
  src/lib/AudioUltra/Controls/Player.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/tags/object/Image/Image.js
  src/tags/object/Paragraphs/HtxParagraphs.js
  src/tags/object/Paragraphs/model.js
  src/utils/feature-flags.ts
Labels: fix

#1324 feat: LSDV-3025-11: Add functionality to filter with multiple rules
  src/common/Select/Select.tsx
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterDropdown.tsx
  src/components/Filter/FilterInput.tsx
  src/components/Filter/FilterInterfaces.tsx
  src/components/Filter/FilterRow.styl
  src/components/Filter/FilterRow.tsx
  src/components/Filter/__tests__/Filter.test.tsx
  src/components/Filter/__tests__/FilterRow.test.tsx
  src/components/Filter/__tests__/filter-utils.test.tsx
  src/components/Filter/filter-util.ts
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/components/SidePanels/TabPanels/Tabs.tsx
  tests/functional/specs/outliner/filter.cy.ts
Labels: feat

#1332 chore: LSDV-4993: Fix ESLint to target changed files only
  .github/workflows/eslint.yml
  src/configureStore.js
Labels: chore

#1341 fix: Cypress test runner in parallel mode
  tests/functional/package.json
  tests/functional/yarn.lock
Labels: fix
