Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-01, with the labels that each got.

#1011 fix: DEV-3644: Ensure draft is saved correctly and remains editable
  src/components/CurrentEntity/AnnotationHistory.tsx
  src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#1126 fix: DEV-4025: Label with choice set to multiple was unselecting when using ParagraphLabels
  src/tags/control/Label.js
Labels: fix, Confirmed

#1136 ci: SRE-389: Remove PAT token from PR labler
  .github/workflows/pr-labeler.yml
Labels: ci

#1139 docs: Remove useless color params in KeyPointLabels
  src/tags/control/KeyPointLabels.js
Labels: docs

#1127 fix: DEV-3730: Make shortcut buttons work without focusing textarea
  e2e/fragments/AtOutliner.js
  e2e/tests/shortcuts.test.js
  src/tags/control/TextArea/TextArea.js
  src/utils/feature-flags.ts
Labels: fix, Confirmed

#1140 docs: DEV-4153: Small docs fixes
  src/regions/AudioRegion.js
  src/regions/AudioRegion/AudioRegionModel.js
  src/regions/AudioRegion/AudioUltraRegionModel.js
  src/tags/control/Brush.js
  src/tags/visual/Repeater.js
Labels: docs

#1144 ci: SRE-391: Assign job permissions
  .github/workflows/build_bundle.yml
  .github/workflows/cancel_cicd_pipeline.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/eslint.yml
  .github/workflows/unit_tests.yml
Labels: ci

#1111 fix: DEV-3941: Enable adjusting player head position using TimeBox
  src/components/SidePanels/DetailsPanel/RegionEditor.tsx
  src/components/TimeDurationControl/TimeBox.tsx
  src/components/TimeDurationControl/TimeDurationControl.tsx
  src/components/Timeline/Controls.tsx
  src/tags/object/AudioUltra/view.tsx
  src/utils/InputMask.ts
Labels: fix, Confirmed

#1124 fix: DEV-4085: Fix error during submit
  src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#1146 fix: DEV-3919: Pin regions to the bottom in Preview
  src/components/SidePanels/SidePanels.styl
Labels: fix, Confirmed

#1154 fix: DEV-3919: Outliner on a narrow screen
  src/components/App/App.styl
Labels: fix, Confirmed

#1157 chore: DEV-4230: Add tests for Outliner
  e2e/fragments/AtDetails.js
  e2e/fragments/AtPanels.js
  e2e/fragments/AtVideoView.js
  e2e/helpers/MouseActions.js
  e2e/tests/helpers.js
  e2e/tests/outliner.test.js
  e2e/tests/regression-tests/video-meta.test.js
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
Labels: chore

#1150 fix: DEV-3694: Fix video zooming
  src/tags/object/Video/HtxVideo.js
Labels: fix, Confirmed

#1158 chore: DEV-3638: Add test for Numpad hotkeys
  e2e/tests/helpers.js
  e2e/tests/regression-tests/numpad-hotkeys.test.js
Labels: chore

#1138 feat: DEV-4034: Rendering performance improvements for large-duration audio
  package.json
  scripts/postinstall.sh
  src/components/Timeline/Controls/AudioControl.tsx
  src/lib/AudioUltra/Controls/Player.ts
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/AudioDecoderPool.ts
  src/lib/AudioUltra/Media/ChannelData.ts
  src/lib/AudioUltra/Media/ChannelDataWorker.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/lib/AudioUltra/Visual/Layer.ts
  src/lib/AudioUltra/Visual/Loader.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
  src/lib/AudioUltra/Waveform.ts
  src/lib/AudioUltra/react/index.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
  webpack.config-builder.js
  yarn.lock
Labels: feat, Confirmed

#1106 chore: DEV-3994: Add PR checklist template
  .github/pull_request_template.md
Labels: chore, Confirmed

#1141 feat: DEV-4028: Use $fps from task for frameRate
  src/tags/object/Video/Video.js
Labels: feat

#1163 fix: LSDV-1140: Select region when regions is dragged
  e2e/fragments/AtAudioView.js
  e2e/tests/audio.test.js
  src/lib/AudioUltra/Regions/Segment.ts
Labels: fix, breaking

#1165 fix: Lse-release 2.4.1: Revert feat: DEV-4034
  package.json
  scripts/postinstall.sh
  src/components/Timeline/Controls/AudioControl.tsx
  src/lib/AudioUltra/Controls/Player.ts
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/AudioDecoderPool.ts
  src/lib/AudioUltra/Media/ChannelData.ts
  src/lib/AudioUltra/Media/ChannelDataWorker.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/lib/AudioUltra/Visual/Layer.ts
  src/lib/AudioUltra/Visual/Loader.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
  src/lib/AudioUltra/Waveform.ts
  src/lib/AudioUltra/react/index.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
  webpack.config-builder.js
  yarn.lock
Labels: fix, breaking

#1156 fix: DEV-4178: Disable postpone button when no comments left
  src/components/TopBar/CurrentTask.js
  src/utils/feature-flags.ts
Labels: fix

#1167 fix: LSDV-1066: Bbox can be resized if ImageView is zoomed
  e2e/tests/image.transformer.test.js
  src/components/ImageTransformer/ImageTransformer.js
  src/tags/object/Image.js
  src/utils/feature-flags.ts
Labels: fix, breaking
