Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-11, with the labels that each got.

#1592 feat: LEAP-58: Proxy URL for Taxonomy if possible
  src/env/development.js
  src/env/production.js
  src/stores/AppStore.js
  src/tags/control/Taxonomy/Taxonomy.js
Labels: feat

#1598 fix: OPTIC-113: Draft save on switch history and exit
  src/components/CurrentEntity/AnnotationHistory.tsx
  src/stores/Annotation/Annotation.js
Labels: fix, Confirmed

#1530 fix: LEAP-16: Add validation to contextual scrolling
  src/tags/object/Paragraphs/HtxParagraphs.js
  src/tags/object/Paragraphs/Phrases.js
Labels: fix

#1565 perf: LEAP-32: Improve performance of zooming at Image Segmentation
  e2e/fragments/AtImageView.js
  e2e/setup/feature-flags.js
  e2e/tests/helpers.js
  src/components/ImageTransformer/ImageTransformer.js
  src/components/ImageView/ImageView.js
  src/mixins/KonvaRegion.js
  src/regions/BrushRegion.js
  src/regions/EllipseRegion.js
  src/regions/KeyPointRegion.js
  src/regions/PolygonPoint.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/tags/object/Image/Image.js
  src/utils/feature-flags.ts
  tests/functional/data/image_segmentation/image_position.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/image_segmentation/image_position.cy.ts
  tests/functional/specs/relations/image_rectangle_regions.cy.ts
  tests/functional/yarn.lock
Labels: Confirmed, perf

#1610 fix: LEAP-345: Fix taxonomy items collapsing when dropdown is closed
  src/components/NewTaxonomy/NewTaxonomy.tsx
  src/components/NewTaxonomy/TaxonomySearch.tsx
Labels: fix, Confirmed

#1569 docs: Small fixes for tag params doc
  src/regions/ParagraphsRegion.js
  src/tags/object/Image/Image.js
  src/tags/object/Paragraphs/model.js
Labels: docs

#1087 fix: DEV-3982: Fix duplicated March in DateTime
  src/tags/control/DateTime.js
Labels: fix

#927 docs: Add paragraphs example with audio
  src/tags/object/Paragraphs/model.js
Labels: docs

#1611 fix: OPTIC-142: Submit and exit style update
  src/common/Dropdown/DropdownComponent.tsx
  src/components/BottomBar/Controls.js
  src/components/BottomBar/Controls.styl
Labels: fix, Confirmed

#1612 feat: LEAP-336: Collapsible cards in Ranker
  src/components/Ranker/Column.tsx
  src/components/Ranker/Item.tsx
  src/components/Ranker/Ranker.module.scss
  src/components/Ranker/Ranker.tsx
  src/tags/control/Ranker.js
Labels: feat, Confirmed

#1577 docs: DOC-121: Update Taxonomy tag page for external taxonomy
  src/tags/control/Taxonomy/Taxonomy.js
Labels: docs

#1616 fix: LEAP-364: Fix crosshair functionality
  src/components/ImageView/ImageView.js
  tests/functional/data/image_segmentation/crosshair.ts
  tests/functional/package.json
  tests/functional/specs/image_segmentation/crosshair.cy.ts
  tests/functional/yarn.lock
Labels: fix, Confirmed

#1618 ci: LEAP-296: Remove SSH Agent from Cypress step
  .github/workflows/fun_tests.yml
Labels: ci

#1619 ci: LEAP-296: Fix link to ls-frontend-test repo
  tests/functional/package.json
  tests/functional/yarn.lock
Labels: ci

#1566 fix: LEAP-208: Make Labeling Settings clickable
  src/components/Settings/Settings.js
  src/components/Settings/Settings.styl
Labels: fix, Confirmed

#1466 fix: ImageView middle click drag: prevent page scrolling
  src/components/ImageView/ImageView.js
Labels: fix

#1605 fix: LEAP-31: Fix functioning of auto annotations
  src/components/App/App.js
  src/mixins/AreaMixin.js
  src/mixins/Regions.js
  src/regions/Area.js
  src/stores/Annotation/Annotation.js
  src/stores/AppStore.js
  src/tags/control/Base.js
  src/tags/control/TextArea/TextArea.js
  src/tags/object/Base.js
  src/tags/object/Image/Image.js
  src/tags/object/Paragraphs/model.js
  src/tags/object/RichText/view.js
  src/tools/Base.js
  src/tools/Manager.js
  tests/functional/data/auto_annotation/auto_accept.ts
  tests/functional/package.json
  tests/functional/specs/auto_annotation/auto_accept.cy.ts
  tests/functional/yarn.lock
Labels: fix, Confirmed

#1626 fix: LEAP-377: Polygon points can be moved correctly
  src/regions/PolygonRegion.js
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix, Confirmed

#1629 fix: LEAP-377: Polygon points can be moved correctly (#1626)
  src/regions/PolygonRegion.js
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix

#1630 fix: LEAP-419: Fix brush issues appeared after fixing zoom performance
  e2e/tests/regression-tests/image-ctrl-drawing.test.js
  src/regions/BrushRegion.js
  src/tags/object/Image/Image.js
  src/tools/Base.js
  src/tools/Brush.js
  src/tools/Erase.js
  src/tools/MagicWand.js
  src/tools/Zoom.js
  tests/functional/data/image_segmentation/tools/brush.ts
  tests/functional/data/image_segmentation/tools/magic-wand.ts
  tests/functional/specs/image_segmentation/tools/brush.cy.ts
  tests/functional/specs/image_segmentation/tools/magic-wand.cy.ts
Labels: fix

#1625 fix: LEAP-419: Fix brush issues appeared after fixing zoom performance
  e2e/tests/regression-tests/image-ctrl-drawing.test.js
  src/regions/BrushRegion.js
  src/tags/object/Image/Image.js
  src/tools/Base.js
  src/tools/Brush.js
  src/tools/Erase.js
  src/tools/MagicWand.js
  src/tools/Zoom.js
  tests/functional/data/image_segmentation/tools/brush.ts
  tests/functional/data/image_segmentation/tools/magic-wand.ts
  tests/functional/package.json
  tests/functional/specs/image_segmentation/tools/brush.cy.ts
  tests/functional/specs/image_segmentation/tools/magic-wand.cy.ts
  tests/functional/yarn.lock
Labels: fix, Confirmed

#1627 docs: DOC-161: Add beta tag for external taxonomy
  src/tags/control/Taxonomy/Taxonomy.js
Labels: docs
