Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-10, with the labels that each got.

#1239 fix: LSDV-1476: Fix selected=true for Taxonomy
  examples/classification_mixed/config.xml
  src/env/development.js
  src/env/production.js
  src/mixins/ProcessAttrs.js
  src/stores/Annotation/Annotation.js
  src/stores/AppStore.js
  src/tags/control/Choice.js
  src/tags/control/Taxonomy/Taxonomy.js
  src/utils/feature-flags.ts
  tests/functional/data/control_tags/taxonomy.ts
  tests/functional/package.json
  tests/functional/specs/control_tags/taxonomy.cy.ts
  tests/functional/tsconfig.json
  tests/functional/yarn.lock
Labels: fix, breaking

#1554 fix: LSDV-5044: Add queueTotal to lsfProperties from project
  src/components/BottomBar/CurrentTask.js
  src/components/TopBar/CurrentTask.js
  src/stores/AppStore.js
  src/utils/feature-flags.ts
Labels: fix

#1580 fix: LEAP-250: Fix maxUsages for New Taxonomy
  src/components/NewTaxonomy/NewTaxonomy.tsx
Labels: fix, Confirmed

#1555 fix: LEAP-33: Fixes for labels by Taxonomy
  src/components/NewTaxonomy/NewTaxonomy.styl
  src/components/NewTaxonomy/NewTaxonomy.tsx
  src/components/Node/Node.tsx
  src/components/Taxonomy/Taxonomy.tsx
  src/mixins/HighlightMixin.js
  src/mixins/SelectedChoiceMixin.js
  src/regions/Result.js
  src/tags/control/Choice.js
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix

#1584 fix: LEAP-252: Use standard error message for Async Taxonomy errors
  .github/workflows/e2e_tests.yml
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix, Confirmed

#1586 fix: LEAP-255: Parse username and password from basic auth URL and use for API calls
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix, Confirmed

#1595 feat: LEAP-235: Use selected items with full info
  src/components/NewTaxonomy/NewTaxonomy.tsx
  src/tags/control/Taxonomy/Taxonomy.js
  tests/functional/data/control_tags/taxonomy.ts
  tests/functional/specs/control_tags/taxonomy.cy.ts
Labels: feat, Confirmed

#1583 fix: LEAP-256: Include the 'legacy' property in the 'Taxonomy' tag
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix, Confirmed

#1603 fix: LEAP-306: Fix security vulnerabilities
  e2e/package.json
  e2e/yarn.lock
  package.json
  tests/functional/package.json
  tests/functional/specs/audio/audio_paragraphs.cy.ts
  tests/functional/yarn.lock
  yarn.lock
Labels: fix, Confirmed

#1600 fix: LEAP-295: Fix error styles in LS modals
  src/components/ErrorMessage/ErrorMessage.module.scss
Labels: fix, Confirmed

#1489 chore: LEAP-221: Remove Taxonomy flags
  e2e/tests/nested-choices.test.js
  e2e/tests/regression-tests/dynamic-choices.test.js
  e2e/tests/regression-tests/preselected-choices.test.js
  e2e/tests/taxonomy.test.js
  src/stores/Annotation/Annotation.js
  src/tags/control/Choice.js
  src/tags/control/Choices.js
  src/tags/control/Labels/Labels.js
  src/tags/control/Taxonomy/Taxonomy.js
  src/utils/feature-flags.ts
  tests/functional/data/control_tags/choice.ts
  tests/functional/package.json
  tests/functional/specs/control_tags/choice.cy.ts
  tests/functional/specs/control_tags/taxonomy.cy.ts
  tests/functional/yarn.lock
Labels: chore

#1601 fix: LEAP-218: Improve performance of search
  src/components/NewTaxonomy/NewTaxonomy.tsx
  src/components/NewTaxonomy/TaxonomySearch.styl
  src/components/NewTaxonomy/TaxonomySearch.tsx
  src/tags/control/Taxonomy/Taxonomy.js
  src/utils/feature-flags.ts
  tests/functional/specs/control_tags/taxonomy.cy.ts
Labels: fix, Confirmed

#1609 fix: LEAP-314: Fix Github vulnerabilities
  package.json
  yarn.lock
Labels: fix
