Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-12, with the labels that each got.

#1631 fix: LEAP-89: Fix rendering of relation arrow in MIG case
  src/components/RelationsOverlay/NodesConnector.js
Labels: fix, Confirmed

#1638 fix: OPTIC-341: CSS inconsistencies which cause conflicts in MonoRepo builds
  src/components/BottomBar/Controls.styl
  src/components/Comments/CommentForm.styl
  src/components/SidePanels/TabPanels/PanelTabsBase.styl
  src/components/TopBar/Controls.styl
Labels: fix

#1639 fix: OPTIC-341: Incorrect icon width causing layout issues with TabPanels in monorepo
  src/components/SidePanels/TabPanels/PanelTabsBase.tsx
  src/components/SidePanels/TabPanels/Tabs.tsx
Labels: fix

#1645 ci: PLATE-775: ChatOps: Instant Workflow Run link + reaction token
  .github/workflows/git-command.yml
  .github/workflows/jira-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: ci

#1646 fix: LEAP-466: Don't sanitize text tasks
  src/tags/object/RichText/model.js
  src/utils/feature-flags.ts
Labels: fix

#1647 fix: LEAP-466: Don't sanitize text tasks (#1646)
  src/tags/object/RichText/model.js
  src/utils/feature-flags.ts
Labels: fix

#1641 fix: LEAP-368: Don't add `hidden` and `locked` to undo history
  src/mixins/Regions.js
Labels: fix, Confirmed

#1648 fix: LEAP-381: Remove excess regexp from BEM module
  src/utils/bem.ts
Labels: fix
