Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-08, with the labels that each got.

#1519 fix: LSDV-5460: Paragraph is sync with audio and isn't automatically pausing anymore
  src/tags/object/Paragraphs/model.js
Labels: fix

#1518 fix: LSDV-4620-4: Optimize outliner region tree rendering
  e2e/fragments/AtOutliner.js
  e2e/setup/feature-flags.js
  examples/dialogue_analysis/annotations/1.json
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.styl
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/components/SidePanels/PanelBase.tsx
  src/components/SidePanels/TabPanels/PanelTabsBase.styl
  src/components/SidePanels/TabPanels/Tabs.styl
  src/components/SidePanels/TabPanels/Tabs.tsx
  src/tags/control/TextArea/TextArea.styl
  src/utils/feature-flags.ts
  tests/functional/cypress/support/e2e.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/outliner/hide-all.cy.ts
  tests/functional/specs/outliner/region_tree.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1522 fix: LSDV-5446: Fix disappearing icons
  src/utils/reactCleaner.js
  tests/functional/yarn.lock
Labels: fix

#1214 fix: LSDV-4600: Lead time for TextArea
  e2e/examples/classification.js
  e2e/fragments/AtTextAreaView.js
  e2e/tests/readonly-tests/readonly-annotations/classification-annotation-readonly.test.js
  e2e/tests/text-area.test.js
  examples/classification_mixed/config.xml
  examples/classification_mixed/index.js
  src/components/Entity/Entity.js
  src/components/SidePanels/DetailsPanel/RegionDetails.tsx
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/env/development.js
  src/mixins/LeadTime.ts
  src/mixins/Normalization.ts
  src/regions/Area.js
  src/regions/Result.js
  src/regions/TextAreaRegion.js
  src/tags/control/TextArea/TextArea.js
  src/tags/control/TextArea/TextAreaRegionView.js
  src/utils/feature-flags.ts
  tests/functional/data/control_tags/textarea.ts
  tests/functional/specs/control_tags/textarea.cy.ts
Labels: fix, breaking

#1526 feat: LSDV-5451: LSDV-5452: Improved Taxonomy
  e2e/fragments/AtTaxonomy.js
  e2e/tests/taxonomy.test.js
  src/components/NewTaxonomy/NewTaxonomy.tsx
  src/components/SidePanels/DetailsPanel/RegionLabels.tsx
  src/mixins/AreaMixin.js
  src/mixins/HighlightMixin.js
  src/regions/Result.js
  src/stores/Annotation/Annotation.js
  src/stores/RegionStore.js
  src/tags/control/Labels/Labels.js
  src/tags/control/Taxonomy/Taxonomy.js
  src/tags/control/Taxonomy/Taxonomy.styl
  src/tags/object/RichText/model.js
  src/utils/feature-flags.ts
Labels: feat

#1528 chore: OPTIC-4: Remove any profanity from sample data
  e2e/examples/audio-paragraphs.js
  e2e/examples/text-paragraphs.js
  e2e/tests/paragraphs-filter.test.js
  e2e/tests/sync/audio-paragraphs.test.js
  e2e/tests/sync/audio-video-paragraphs.test.js
  examples/audio_video_paragraphs/annotations/1.json
  examples/audio_video_paragraphs/tasks.json
  examples/phrases/annotations/1.json
  examples/phrases/tasks.json
  examples/rich_text_plain/annotations/1.json
  examples/rich_text_plain/tasks.json
  tests/functional/data/audio/audio_paragraphs.ts
Labels: chore

#1483 docs: LSDV-5343: Docs for visibleWhen; remove FF_DEV_1372
  e2e/tests/nested.test.js
  e2e/tests/required.test.js
  src/mixins/Visibility.js
  src/regions/Result.js
  src/tags/control/Choices.js
  src/tags/visual/View.js
  src/utils/feature-flags.ts
Labels: docs

#1529 fix: OPTIC-6: Splitchannel audio render option
  src/tags/object/AudioUltra/model.js
  tests/functional/output/snapshots/Audio -- Renders audio with merged channels by default.snap.png
  tests/functional/output/snapshots/Audio -- Renders separate audio channels with splitchannels=true.snap.png
  tests/functional/specs/audio/audio.cy.ts
Labels: fix

#1534 fix: OPTIC-6: Splitchannel audio render option (#1529)
  src/tags/object/AudioUltra/model.js
  tests/functional/output/snapshots/Audio -- Renders audio with merged channels by default.snap.png
  tests/functional/output/snapshots/Audio -- Renders separate audio channels with splitchannels=true.snap.png
  tests/functional/specs/audio/audio.cy.ts
Labels: fix

#1527 fix: LSDV-5523: Check tag has context scroll true to show the toggle
  src/tags/object/Paragraphs/HtxParagraphs.js
Labels: fix

#1540 fix: LSDV-5544: Fix RichText tag in non-Chromium browsers
  src/tags/object/RichText/domManager.ts
  tests/functional/package.json
  tests/functional/yarn.lock
Labels: fix

#1548 fix: LSDV-5523, LSDV-5071: Check tag has context scroll true to show the toggle, secure secret key
  src/tags/object/Paragraphs/HtxParagraphs.js
Labels: fix

#1549 ci: Fix several vulnerabilities from dependabot
  yarn.lock
Labels: ci

#1537 fix: LEAP-14: Fixes for New Taxonomy
  src/components/NewTaxonomy/NewTaxonomy.tsx
  src/tags/control/Taxonomy/Taxonomy.js
Labels: fix
