Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-02, with the labels that each got.

#1021 fix: DEV-3666: Fix maxUsages on regions creation
  e2e/examples/data/sample-sin.json
  e2e/fragments/AtAudioView.js
  e2e/fragments/AtImageView.js
  e2e/fragments/AtParagraphs.js
  e2e/fragments/AtRichText.js
  e2e/fragments/AtTimeSeries.js
  e2e/tests/maxUsage.test.js
  src/mixins/DrawingTool.js
  src/mixins/SelectedModel.js
  src/tags/object/Base.js
  src/tags/object/Image.js
  src/tags/object/Paragraphs/Model.js
  src/tools/Brush.js
  src/tools/KeyPoint.js
  src/utils/feature-flags.ts
Labels: fix

#1161 fix: DEV-3928: Make error messages more configurable
  src/components/ImageView/ImageView.js
  src/components/Waveform/Waveform.js
  src/stores/AppStore.js
  src/tags/object/Audio.js
  src/tags/object/AudioNext/view_old.js
  src/tags/object/Table.js
  src/tags/object/TimeSeries.js
  src/utils/messages.js
Labels: fix, breaking, Confirmed

#1130 fix: DEV-4075: Fix taxonomy items overlap on search
  e2e/fragments/AtTaxonomy.js
  e2e/fragments/AtTimeSeries.js
  e2e/fragments/LabelStudio.js
  e2e/plugins/featureFlags.js
  e2e/tests/helpers.js
  e2e/tests/taxonomy.test.js
  src/components/Taxonomy/Taxonomy.module.scss
  src/components/Taxonomy/Taxonomy.tsx
  src/components/TreeStructure/TreeStructure.tsx
  src/utils/feature-flags.ts
Labels: fix, Confirmed

#1171 fix: LSDV-1148: Hotkeys namespaces
  e2e/tests/regression-tests/hotkey.test.js
  src/core/Hotkey.ts
  src/utils/feature-flags.ts
Labels: fix, breaking

#1178 fix: LSDV-4539: Don't show history for wrong anno
  e2e/tests/taxonomy.test.js
  src/stores/AppStore.js
Labels: fix, breaking

#1168 fix: LSDV-3004: Region with per-regions is broken when user click on assigned label
  e2e/tests/nested.test.js
  src/mixins/AreaMixin.js
  src/tags/control/Label.js
Labels: fix, breaking

#1155 fix: DEV-3731: Fix keeping center of zoom at image on resize
  e2e/fragments/AtImageView.js
  e2e/fragments/AtOutliner.js
  e2e/tests/helpers.js
  e2e/tests/regression-tests/image-zoom-position.test.js
  e2e/tests/regression-tests/image-zoom-transform.test.js
  src/components/SidePanels/PanelBase.styl
  src/tags/object/Image.js
Labels: fix

#1176 feat: LSDV-E-131: Labels inside regions
  src/lib/AudioUltra/Regions/Region.ts
  src/lib/AudioUltra/Regions/Regions.ts
  src/lib/AudioUltra/Regions/Segment.ts
  src/lib/AudioUltra/Visual/Layer.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
  src/lib/AudioUltra/Waveform.ts
  src/lib/AudioUltra/react/index.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
Labels: feat, breaking

#1142 fix: DEV-4087: Fix multiple labels in Outliner
  e2e/fragments/AtDetails.js
  src/components/SidePanels/DetailsPanel/DetailsPanel.styl
  src/components/SidePanels/DetailsPanel/RegionDetails.styl
  src/components/SidePanels/DetailsPanel/RegionDetails.tsx
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
  src/components/SidePanels/DetailsPanel/RegionLabels.tsx
  src/mixins/WithStates.js
  src/regions/AudioRegion.js
  src/regions/BrushRegion.js
  src/regions/EllipseRegion.js
  src/regions/KeyPointRegion.js
  src/regions/ParagraphsRegion.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/regions/RichTextRegion.js
  src/regions/TextAreaRegion.js
  src/regions/TimeSeriesRegion.js
  src/regions/VideoRectangleRegion.js
  src/regions/VideoRegion.js
  types/Regions.d.ts
Labels: fix, Confirmed

#1162 chore: LSDV-1376: Remove ff for 2480 (empty nodes)
  src/utils/feature-flags.ts
  src/utils/selection-tools.js
Labels: chore, breaking

#1180 fix: LSDV-4539: Don't show history for wrong annotation
  src/stores/AppStore.js
Labels: fix, breaking

#1099 chore: DEV-4026: E2E for TimeSeries with huge data and overview manipulations
  e2e/fragments/AtTimeSeries.js
  e2e/helpers/MouseActions.js
  e2e/tests/timeseries.test.js
  src/tags/object/TimeSeries.js
Labels: chore

#1182 fix: LSDV-4541: Audio segment is being deleted by pressing delete button
  e2e/tests/audio.test.js
  src/core/settings/keymap.json
  src/tags/object/AudioUltra/view.tsx
Labels: fix, breaking

#1166 fix: LSDV-4532: Audio v3 visual data is offset to sound playback
  e2e/fragments/AtAudioView.js
  e2e/tests/audio/audio-controls.test.js
  e2e/tests/audio/audio-paragraphs.test.js
  e2e/tests/audio/audio-regions.test.js
  package.json
  scripts/postinstall.sh
  src/components/Timeline/Controls/AudioControl.tsx
  src/lib/AudioUltra/Common/Utils.ts
  src/lib/AudioUltra/Controls/Player.ts
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/AudioDecoderPool.ts
  src/lib/AudioUltra/Media/ChannelData.ts
  src/lib/AudioUltra/Media/ChannelDataWorker.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/lib/AudioUltra/Visual/Layer.ts
  src/lib/AudioUltra/Visual/Loader.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
  src/lib/AudioUltra/Waveform.ts
  src/lib/AudioUltra/react/index.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
  webpack.config-builder.js
  yarn.lock
Labels: fix, feat

#1181 feat: LSDV-3936: Task history is stored on the backend
  src/components/App/App.js
  src/stores/AppStore.js
Labels: feat, breaking

#1153 fix: DEV-2019: Sync video timeline seeker with frame position
  e2e/fragments/AtVideoView.js
  e2e/tests/regression-tests/video-timeline-seek-indicator.test.js
  src/components/Timeline/Seeker.tsx
  src/components/Timeline/SideControls/FramesControl.tsx
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/Views/Frames/Frames.tsx
  src/env/development.js
  src/stores/Annotation/Annotation.js
  src/tags/object/Video/HtxVideo.js
Labels: fix

#723 fix: DEV-1020: Validation error about unknown tag
  src/core/DataValidator/ConfigValidator.js
Labels: fix, Confirmed

#1195 chore: LSDV-4592: Add tests to validate if ghost regions are created on AudioV3
  e2e/fragments/AtAudioView.js
  e2e/tests/audio/audio-regions.test.js
Labels: chore, breaking

#1196 fix: LSDV-4627: App crash with FF for DEV-3391 is on
  e2e/tests/image.magic-wand.test.js
  src/core/Registry.ts
  src/tags/control/MagicWand.js
Labels: fix, breaking

#1185 feat: LSDV-3028: Audio v3 dual channel render
  e2e/fragments/AtAudioView.js
  e2e/tests/audio/audio-controls.test.js
  package.json
  scripts/postinstall.sh
  src/lib/AudioUltra/Common/Worker/index.ts
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/AudioDecoderPool.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/SplitChannel.ts
  src/lib/AudioUltra/Media/SplitChannelWorker.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/lib/AudioUltra/Regions/Segment.ts
  src/lib/AudioUltra/Visual/Layer.ts
  src/lib/AudioUltra/Visual/LayerGroup.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
  src/lib/AudioUltra/Waveform.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
  src/utils/feature-flags.ts
  yarn.lock
Labels: feat, breaking

#1193 fix: LSDV-3009: Fix draft saving stuck
  src/stores/Annotation/Annotation.js
  src/utils/feature-flags.ts
Labels: fix, breaking

#1149 feat: DEV-4187: Select regions without 300ms lag
  src/mixins/KonvaRegion.js
Labels: feat, Confirmed

#1076 chore: DEV-3947: Add e2e tests coverage to reports
  .github/workflows/build_bundle.yml
  .github/workflows/cicd_pipeline.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/tests_coverage.yml
  .github/workflows/unit_tests.yml
  codecov.yml
  e2e/codecept.conf.js
  e2e/coverage-to-istanbul.js
  e2e/package.json
  e2e/plugins/istanbulСoverage.js
  e2e/steps_file.js
  jest.config.js
  nyc.config.js
  package.json
  src/configureStore.js
  src/tags/control/Choice.js
  src/tags/control/TextArea/TextArea.js
  webpack.config-builder.js
Labels: chore

#1190 fix: LSDV-1023: Add audio error handler to audio v3
  e2e/fragments/AtAudioView.js
  e2e/fragments/AtVideoView.js
  e2e/tests/audio/audio-errors.test.js
  e2e/tests/image.magic-wand.test.js
  e2e/tests/regression-tests/video-timeline-seek-indicator.test.js
  src/components/ErrorMessage/ErrorMessage.js
  src/components/Timeline/SideControls/FramesControl.tsx
  src/components/Timeline/Timeline.tsx
  src/components/Timeline/Views/Frames/Frames.tsx
  src/lib/AudioUltra/Common/Worker/index.ts
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/lib/AudioUltra/Visual/Layer.ts
  src/lib/AudioUltra/Visual/LayerGroup.ts
  src/lib/AudioUltra/Visual/Visualizer.ts
  src/lib/AudioUltra/Waveform.ts
  src/lib/AudioUltra/react/index.ts
  src/mixins/KonvaRegion.js
  src/stores/Annotation/Annotation.js
  src/tags/control/Choice.js
  src/tags/control/MagicWand.js
  src/tags/control/TextArea/TextArea.js
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
  src/tags/object/Video/HtxVideo.js
  src/utils/messages.js
Labels: fix, breaking

#952 fix: DEV-3627: Video type unsupported modal misfires fix
  src/components/VideoCanvas/VideoCanvas.tsx
  src/components/VideoCanvas/VirtualVideo.tsx
Labels: fix

#1217 fix: LSDV-4670: Fix frontend build
  package.json
  src/components/SidePanels/Components/LockButton.tsx
  yarn.lock
Labels: fix, breaking

#1220 docs: Improve dynamic Choices example, add html attribute
  package.json
  src/tags/control/Choices.js
  src/tags/control/Number.js
  src/tags/visual/Repeater.js
  yarn.lock
Labels: docs

#1212 fix: LSDV-4572: Audio playback and playhead briefly get out of sync
  src/lib/AudioUltra/Controls/Player.ts
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
Labels: fix

#1213 fix: LSDV-4542: Hiding an audio segment and select a segment below no longer works
  e2e/fragments/AtSidebar.js
  e2e/tests/audio/audio-regions.test.js
  src/components/Entities/RegionItem.js
  src/lib/AudioUltra/Regions/Regions.ts
Labels: fix, breaking
