Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-05, with the labels that each got.

#1339 fix: LSDV-5010: View all panel padding removed
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
Labels: fix

#1323 chore: LSDV-4894: Update to NodeJS LTS
  .github/workflows/build_bundle.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/eslint.yml
  .github/workflows/fun_tests.yml
  .github/workflows/release-set-version.yml
  .github/workflows/unit_tests.yml
  e2e/tests/image.magic-wand.test.js
  package.json
  src/env/development.js
  webpack.config-builder.js
  yarn.lock
Labels: chore

#1346 fix: LSDV-4998: Fix missed dynamic children on task switch
  src/stores/AppStore.js
  src/utils/feature-flags.ts
Labels: fix

#1340 fix: LSDV-5011: In view all mode there should be no bottom bar
  src/components/BottomBar/BottomBar.js
Labels: fix

#1343 feat: LSDV: 5016 Outliner manual group sort order arrow
  src/components/SidePanels/OutlinerPanel/ViewControls.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
Labels: feat

#1342 fix: LSDV-4960: Sort annotations by creation date instead of pk
  src/components/AnnotationsCarousel/AnnotationsCarousel.tsx
Labels: fix

#1358 fix: Tag documentation script
  scripts/create-docs.js
Labels: fix

#1353 feat: LSDV-3025-13: Add how many filter rules are applied
  src/components/Filter/Filter.styl
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterInterfaces.tsx
  src/components/Filter/__tests__/Filter.test.tsx
Labels: feat

#1362 feat: LSDV-5069: Create new defaults for panels and tabs
  src/components/SidePanels/TabPanels/utils.ts
Labels: feat

#1348 fix: LSDV-4726: DateTime min/max
  e2e/codecept.conf.js
  e2e/fragments/AtDateTime.ts
  e2e/helpers/DateTime.ts
  e2e/tests/date-time.test.js
  src/mixins/Required.js
  src/regions/Result.js
  src/stores/Annotation/Annotation.js
  src/tags/control/DateTime.js
  src/tags/control/Labels/Labels.js
  src/tags/control/TimeSeriesLabels.js
Labels: fix

#1356 feat: LSDV-3025-15: Add a message in the bottom of the outliner when user creates a new rule of filtering
  src/assets/icons/outliner/index.ts
  src/assets/icons/outliner/info.svg
  src/components/Filter/Filter.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.styl
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
Labels: feat

#1359 feat: PROD-309: Add hint for Choice
  src/common/Tooltip/Tooltip.tsx
  src/components/Taxonomy/Taxonomy.tsx
  src/tags/control/Choice.js
  src/tags/control/Choices.js
  src/tags/control/Taxonomy/Taxonomy.js
  src/utils/feature-flags.ts
  tests/functional/data/control_tags/choice.ts
  tests/functional/data/control_tags/taxonomy.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/control_tags/choice.cy.ts
  tests/functional/specs/control_tags/taxonomy.cy.ts
  tests/functional/yarn.lock
Labels: feat

#1354 feat: LSDV-3025-14: Implement empty state when outliner filter returns empty
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
Labels: feat

#1351 fix: LSDV-4601: Show correct author of draft
  src/stores/Annotation/store.js
  src/utils/__tests__/utilities.test.js
  src/utils/utilities.ts
Labels: fix

#1360 feat: LSDV-5033: Add the option to use WebAudioPlayer for Audio
  .prettierrc
  src/lib/AudioUltra/Controls/Html5Player.ts
  src/lib/AudioUltra/Controls/Player.ts
  src/lib/AudioUltra/Controls/WebAudioPlayer.ts
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/BaseAudioDecoder.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/lib/AudioUltra/Media/WebAudioDecoder.ts
  src/lib/AudioUltra/Waveform.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
  src/utils/feature-flags.ts
Labels: feat

#1367 fix: LSDV-5090: Hidden regions notifications is displaying when filter is applied
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  tests/functional/specs/outliner/filter.cy.ts
Labels: fix

#1368 fix: LSDV-5065: Set filter button active when dropdown is opened
  src/components/Filter/Filter.styl
  src/components/Filter/Filter.tsx
  src/components/Filter/__tests__/Filter.test.tsx
  tests/functional/specs/outliner/filter.cy.ts
Labels: fix

#1373 fix: LSDV-5117: Revert labeling editor CTA buttons color
  src/components/BottomBar/Controls.styl
  tests/functional/specs/outliner/filter.cy.ts
Labels: fix

#1374 fix: LSDV-5116: Change ground truth color to dark
  src/components/CurrentEntity/GroundTruth.js
  src/components/CurrentEntity/GroundTruth.styl
Labels: fix

#1375 fix: LSDV-5119: Minor improvements on labeling ui
  src/common/Dropdown/DropdownComponent.tsx
  src/components/BottomBar/BottomBar.js
  src/components/BottomBar/HistoryActions.styl
  src/components/Filter/Filter.styl
  src/components/Filter/Filter.tsx
  src/components/Settings/Settings.js
  src/components/SidePanels/OutlinerPanel/ViewControls.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/components/TopBar/CurrentTask.js
  src/components/TopBar/CurrentTask.styl
  src/components/TopBar/TopBar.js
Labels: fix

#1377 fix: LSDV-5115: Fix height of tasks header row on quick view
  src/components/TopBar/TopBar.styl
Labels: fix

#1366 fix: LSDV-3859: Update outdated third party js dependencies
  .github/workflows/e2e_tests.yml
  yarn.lock
Labels: fix

#1376 fix: LOPS-170: Labeling ui annotation tab improvements
  src/common/TimeAgo/TimeAgo.tsx
  src/components/AnnotationsCarousel/AnnotationButton.styl
  src/components/TopBar/TopBar.js
  src/components/TopBar/TopBar.styl
Labels: fix

#1355 feat: LSDV-3104: Task navigation standardization
  public/index.html
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
  src/components/BottomBar/CurrentTask.js
  src/components/TopBar/CurrentTask.js
  src/components/TopBar/CurrentTask.styl
  src/components/TopBar/TopBar.styl
  src/stores/AppStore.js
Labels: feat

#1383 chore: LSDV-5109: Rename MIG FF key
  e2e/tests/image-list.test.js
  src/utils/feature-flags.ts
Labels: chore

#1384 fix: ls-release: 1.8.0 hotfix
  public/index.html
  src/common/Button/Button.styl
  src/common/Button/Button.tsx
  src/common/TimeAgo/TimeAgo.tsx
  src/components/AnnotationsCarousel/AnnotationButton.styl
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
  src/components/BottomBar/Controls.js
  src/components/BottomBar/CurrentTask.js
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/components/TopBar/CurrentTask.js
  src/components/TopBar/CurrentTask.styl
  src/components/TopBar/TopBar.js
  src/components/TopBar/TopBar.styl
  src/stores/AppStore.js
Labels: fix

#1385 chore: LSDV-5109: Rename MIG FF key
  e2e/fragments/AtAudioView.js
  e2e/tests/image-list.test.js
  src/utils/feature-flags.ts
Labels: chore

#1387 fix: Fix the problem with combineCoverage and coverageReport tasks in cypress tests
  tests/functional/package.json
Labels: fix

#1389 feat: LSDV-3104: Revert task navigation standardization
  public/index.html
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
  src/components/BottomBar/CurrentTask.js
  src/components/TopBar/CurrentTask.js
  src/components/TopBar/CurrentTask.styl
  src/components/TopBar/TopBar.styl
  src/stores/AppStore.js
Labels: feat

#1390 feat: LSDV-3104: Revert task navigation standardization
  public/index.html
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
  src/components/BottomBar/CurrentTask.js
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/components/TopBar/CurrentTask.js
  src/components/TopBar/CurrentTask.styl
  src/components/TopBar/TopBar.styl
  src/stores/AppStore.js
Labels: feat

#1391 fix: LSDV-5131: Fix Submit button disabled state
  src/common/Button/Button.styl
  src/components/BottomBar/Controls.js
  src/components/BottomBar/Controls.styl
Labels: fix

#1357 fix: LSDV-4992: Fix missed hide all regions button
  src/assets/icons/outliner/eye_closed.svg
  src/assets/icons/outliner/eye_opened.svg
  src/assets/icons/outliner/index.ts
  src/common/Button/Button.tsx
  src/common/Tooltip/Tooltip.tsx
  src/components/SidePanels/OutlinerPanel/ViewControls.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/utils/feature-flags.ts
  tests/functional/data/outliner/hide-all.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/outliner/hide-all.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1393 fix: LSDV-5136: Navigate between tabs in the side panels is not reseting the comments
  src/components/Comments/CommentForm.tsx
  src/components/TopBar/CurrentTask.js
Labels: fix

#1395 fix: LSDV-5162: Fix shifting of annotation tabs on hover
  e2e/tests/regression-tests/annotation-button.test.js
  src/components/AnnotationsCarousel/AnnotationButton.styl
Labels: fix

#1400 fix: 1.8.0 cherrypick 2023 05 25
  e2e/tests/regression-tests/annotation-button.test.js
  src/components/AnnotationsCarousel/AnnotationButton.styl
  src/components/Comments/CommentForm.tsx
  src/components/TopBar/CurrentTask.js
Labels: fix

#1398 fix: LSDV-5160: Hide comments tab on UI Preview
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
Labels: fix

#1402 fix: LSDV-5148: Runtime error when user tries to update/submit duplicated annotation while original is already deleted
  src/components/AnnotationsCarousel/AnnotationButton.tsx
  src/stores/Annotation/store.js
Labels: fix

#1413 fix: 1.8.0 cherrypick 2023 05 26
  src/components/AnnotationsCarousel/AnnotationButton.styl
  src/components/AnnotationsCarousel/AnnotationButton.tsx
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
  src/stores/Annotation/store.js
Labels: fix

#1408 fix: LSDV-5161: Fix confidence score design to match with new labeling ui
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/components/SidePanels/TabPanels/Tabs.tsx
Labels: fix

#1416 fix: LSDV-5167: Ranker undo/redo
  src/components/Ranker/Item.tsx
  src/tags/control/Ranker.js
Labels: fix

#1418 fix: LSDV-5194: Add annotation tab indicator tooltip
  src/assets/icons/comment-check.svg
  src/assets/icons/comment-red.svg
  src/assets/icons/comment-resolved.svg
  src/assets/icons/comment-unresolved.svg
  src/assets/icons/index.tsx
  src/assets/icons/parent-link.svg
  src/assets/icons/plus-circle.svg
  src/assets/icons/view-all.svg
  src/components/AnnotationsCarousel/AnnotationButton.styl
  src/components/AnnotationsCarousel/AnnotationButton.tsx
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
  src/components/AnnotationsCarousel/AnnotationsCarousel.tsx
  src/components/SidePanels/TabPanels/Tabs.tsx
Labels: fix

#1411 fix: LSDV-5145: Regions hover lock consistency
  src/components/SidePanels/Components/LockButton.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
Labels: fix

#1422 chore: 1.8.0 cherrypick 2023 05 30
  src/assets/icons/arrow-left-small.svg
  src/assets/icons/arrow-right-small.svg
  src/assets/icons/collapse-small.svg
  src/assets/icons/comment-check.svg
  src/assets/icons/comment-red.svg
  src/assets/icons/comment-resolved.svg
  src/assets/icons/comment-unresolved.svg
  src/assets/icons/expand-small.svg
  src/assets/icons/index.tsx
  src/assets/icons/parent-link.svg
  src/assets/icons/plus-circle.svg
  src/assets/icons/sort-down-new.svg
  src/assets/icons/sort-up-new.svg
  src/assets/icons/view-all.svg
  src/common/Button/Button.styl
  src/components/AnnotationsCarousel/AnnotationButton.styl
  src/components/AnnotationsCarousel/AnnotationButton.tsx
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
  src/components/AnnotationsCarousel/AnnotationsCarousel.tsx
  src/components/Ranker/Item.tsx
  src/components/SidePanels/Components/LockButton.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.styl
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/components/SidePanels/TabPanels/PanelTabsBase.styl
  src/components/SidePanels/TabPanels/PanelTabsBase.tsx
  src/components/SidePanels/TabPanels/Tabs.tsx
  src/tags/control/Ranker.js
  src/tags/object/Image/Image.js
  src/tags/object/List.js
Labels: chore

#1412 fix: LSDV-5192: Change quick view icon and change hover color
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
Labels: fix

#1421 fix: LSDV-5202: Fix Ranker d-n-d in Preview
  src/components/SidePanels/SidePanels.tsx
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
Labels: fix

#1426 chore: 1.8.0 cherrypick 2023 05 31
  src/components/AnnotationsCarousel/AnnotationsCarousel.styl
  src/components/SidePanels/SidePanels.tsx
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
Labels: chore
