Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-07, with the labels that each got.

#1485 feat: LSDV-5298: Paragraphs must sync seek, play and pause with Audio in both directions
  e2e/tests/sync/audio-paragraphs.test.js
  e2e/tests/sync/audio-video-paragraphs.test.js
  e2e/utils/feature-flags.js
  src/lib/AudioUltra/react/index.ts
  src/mixins/SyncMixin.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/Paragraphs/HtxParagraphs.js
  src/tags/object/Paragraphs/Phrases.js
  src/tags/object/Paragraphs/__tests__/model.test.ts
  src/tags/object/Paragraphs/model.js
  src/tags/object/Video/HtxVideo.js
  src/tags/object/Video/Video.js
  src/utils/TimeSync.ts
  src/utils/feature-flags.ts
Labels: feat

#1460 fix: LSDV-5164: Unselect labels with tools
  src/components/SidePanels/DetailsPanel/RegionLabels.tsx
  src/tags/control/Label.js
  src/tools/Manager.js
Labels: fix

#1497 chore: CI test artifact handling improvement
  .github/actions/download-artifact/action.yml
  .github/actions/upload-artifact/action.yml
  .github/workflows/build_bundle.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/fun_tests.yml
  .github/workflows/tests_coverage.yml
  .github/workflows/unit_tests.yml
Labels: chore

#1494 feat: LSDV-5252: Audio player segment visual identification
  e2e/tests/audio/audio-regions.test.js
  src/components/TimeDurationControl/TimeBox.tsx
  src/components/TimeDurationControl/TimeDurationControl.tsx
  src/components/Timeline/Controls.tsx
  src/lib/AudioUltra/Regions/Regions.ts
  src/lib/AudioUltra/Regions/Segment.ts
  src/lib/AudioUltra/Timeline/Timeline.ts
  src/lib/AudioUltra/Waveform.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/Paragraphs/model.js
  tests/functional/.gitignore
  tests/functional/data/audio/audio_paragraphs.ts
  tests/functional/feature-flags.ts
  tests/functional/output/snapshots/Audio Paragraphs Sync -- Correctly loads with Paragraph segments as Audio segments.snap.png
  tests/functional/output/snapshots/Audio Paragraphs Sync -- Highlights the correct Audio segment whenever it is played or seeked.snap.png
  tests/functional/output/snapshots/audio/audio_paragraphs.cy.ts/Audio Paragraphs Sync -- Correctly loads with Paragraph segments as Audio segments.snap.png
  tests/functional/output/snapshots/audio/audio_paragraphs.cy.ts/HighlightAfterFinishedPlayback.snap.png
  tests/functional/output/snapshots/audio/audio_paragraphs.cy.ts/HighlightOnFirstSeek.snap.png
  tests/functional/package.json
  tests/functional/specs/audio/audio_paragraphs.cy.ts
  tests/functional/specs/outliner/filter.cy.ts
  tests/functional/yarn.lock
Labels: feat

#1492 feat: LSDV-5295: Scroll management of paragraph transcriptions
  e2e/tests/sync/audio-paragraphs.test.js
  src/assets/icons/help.svg
  src/assets/icons/index.tsx
  src/tags/object/Paragraphs/HtxParagraphs.js
  src/tags/object/Paragraphs/Paragraphs.module.scss
  src/tags/object/Paragraphs/Phrases.js
  src/tags/object/Paragraphs/model.js
Labels: feat

#1500 feat: LSDV-5255: Highlight the active paragraph text segment
  e2e/tests/sync/audio-paragraphs.test.js
  e2e/tests/sync/audio-video-paragraphs.test.js
  src/assets/icons/index.tsx
  src/assets/icons/pause.svg
  src/assets/icons/play.svg
  src/tags/object/Paragraphs/Paragraphs.module.scss
  src/tags/object/Paragraphs/Phrases.js
  src/tags/object/Paragraphs/model.js
Labels: feat

#1438 feat: LSDV-5242: TextArea Suggestions for LLM labeling
  src/common/TextArea/TextArea.tsx
  src/components/App/App.js
  src/components/HtxTextBox/HtxTextBox.js
  src/mixins/Regions.js
  src/stores/Annotation/Annotation.js
  src/tags/control/TextArea/TextArea.js
  tests/functional/specs/image_segmentation/tools/rect3point.cy.ts
Labels: feat

#1504 fix: LSDV-5400: LLM suggestions from textarea
  src/tags/control/TextArea/TextArea.js
Labels: fix

#1503 fix: LSDV-5188: Fix show/hide icon that wasn't working if regions was grouped by tools
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
  src/stores/RegionStore.js
  tests/functional/specs/outliner/hide-all.cy.ts
Labels: fix

#1477 fix: LSDV-4937: Label missing from outliner when multiple labels are selected
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/mixins/AreaMixin.js
  src/mixins/DrawingTool.js
  src/tags/object/RichText/model.js
  tests/functional/specs/image_segmentation/image_regions.cy.ts
Labels: fix

#1505 fix: LSDV-5400: Auto accept all annotations
  src/stores/AppStore.js
  src/utils/feature-flags.ts
Labels: fix

#1297 fix: LSDV-4620-3: Fix Richtext performance and functional
  e2e/.eslintrc.js
  e2e/codecept.conf.js
  e2e/examples/text-html.js
  e2e/fragments/AtDetails.js
  e2e/fragments/AtOutliner.js
  e2e/fragments/AtSettings.js
  e2e/fragments/LabelStudio.js
  e2e/helpers/PlaywrightAddon.js
  e2e/plugins/errorsCollector.js
  e2e/setup/feature-flags.js
  e2e/tests/helpers.js
  e2e/tests/regression-tests/richtext.test.js
  e2e/tests/rich-text/rich-text-basic-functional.test.js
  e2e/tests/rich-text/rich-text-edge-cases.test.js
  e2e/tests/rich-text/rich-text-perfomance.test.js
  e2e/tests/rich-text/rich-text-regions-displaying.test.js
  e2e/tests/rich-text/rich-text-regions-interactions.test.js
  e2e/tests/smoke.test.js
  e2e/tests/sync/audio-paragraphs.test.js
  e2e/tests/sync/audio-video-paragraphs.test.js
  src/LabelStudio.js
  src/components/App/App.js
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
  src/core/TimeTraveller.js
  src/core/feature-flags/flags.json
  src/mixins/AnnotationMixin.js
  src/mixins/AreaMixin.js
  src/mixins/DynamicChildrenMixin.js
  src/mixins/HighlightMixin.js
  src/mixins/ReadOnlyMixin.js
  src/mixins/SharedChoiceStore/mixin.js
  src/regions/AliveRegion.tsx
  src/regions/BrushRegion.js
  src/regions/EllipseRegion.js
  src/regions/ImageRegion.js
  src/regions/KeyPointRegion.js
  src/regions/ParagraphsRegion.js
  src/regions/PolygonPoint.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/regions/RichTextRegion.js
  src/stores/Annotation/Annotation.js
  src/stores/AppStore.js
  src/stores/RelationStore.js
  src/tags/object/Image/Image.js
  src/tags/object/Image/ImageEntityMixin.js
  src/tags/object/RichText/RichText.styl
  src/tags/object/RichText/domManager.ts
  src/tags/object/RichText/model.js
  src/tags/object/RichText/view.js
  src/utils/feature-flags.ts
  src/utils/reactCleaner.js
  src/utils/selection-tools.js
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/yarn.lock
Labels: fix

#1508 fix: LSDV-5409: Existing text range cannot be changed into a different label
  src/tags/control/Label.js
Labels: fix

#1493 feat: LSDV-5297: Sort phrases
  __mocks__/global.ts
  src/tags/object/Paragraphs/Phrases.js
  src/tags/object/Paragraphs/__tests__/Phrases.test.tsx
  src/tags/object/Paragraphs/__tests__/model.test.ts
  src/tags/object/Paragraphs/model.js
Labels: feat

#1516 fix: LSDV-5432: Fix losing focus in CodeMirror config editor
  src/tags/object/RichText/domManager.ts
Labels: fix

#1502 fix: LSDV-5256: Stop automatically scrolling if current Paragraph is not on the screen
  e2e/tests/sync/audio-paragraphs.test.js
  src/tags/object/Paragraphs/AuthorFilter.js
  src/tags/object/Paragraphs/HtxParagraphs.js
  src/tags/object/Paragraphs/Paragraphs.module.scss
  src/tags/object/Paragraphs/Phrases.js
  src/tags/object/Paragraphs/__tests__/Phrases.test.tsx
  src/tags/object/Paragraphs/model.js
Labels: fix
