Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-03, with the labels that each got.

#1187 feat: LSDV-4583-6: Image preloading
  e2e/tests/image-list.test.js
  examples/image_list/annotations/1.json
  examples/image_list/config.xml
  examples/image_list/index.ts
  examples/image_list/tasks.json
  examples/image_list_large/annotations/1.json
  examples/image_list_large/config.xml
  examples/image_list_large/index.ts
  examples/image_list_large/tasks.json
  examples/image_list_perregion/annotations/1.json
  examples/image_list_perregion/config.xml
  examples/image_list_perregion/index.ts
  examples/image_list_perregion/tasks.json
  package.json
  src/common/Pagination/Pagination.styl
  src/common/Pagination/Pagination.tsx
  src/common/Tag/Tag.tsx
  src/components/ImageView/Image.js
  src/components/ImageView/Image.styl
  src/components/ImageView/ImageView.js
  src/components/ImageView/ImageView.module.scss
  src/core/Hotkey.ts
  src/core/settings/keymap.json
  src/env/development.js
  src/mixins/DrawingTool.js
  src/mixins/Regions.js
  src/regions/BrushRegion.js
  src/regions/EllipseRegion.js
  src/regions/KeyPointRegion.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/regions/Result.js
  src/stores/RegionStore.js
  src/tags/object/Image.js
  src/tags/object/Image/DrawingRegion.js
  src/tags/object/Image/Image.js
  src/tags/object/Image/ImageEntity.js
  src/tags/object/Image/ImageEntityMixin.js
  src/tags/object/Image/ImageSelection.js
  src/tags/object/Image/ImageSelectionPoint.js
  src/tags/object/Image/index.js
  src/utils/FileLoader.ts
  src/utils/feature-flags.ts
  types/Keymap.d.ts
  webpack.config-builder.js
Labels: feat, breaking

#1202 fix: LSDV-4592: Remove ghost region on AudioV3
  e2e/fragments/AtAudioView.js
  e2e/tests/audio/audio-regions.test.js
  src/lib/AudioUltra/Regions/Regions.ts
  src/lib/AudioUltra/Regions/Segment.ts
  src/tags/object/AudioUltra/model.js
Labels: fix, breaking

#1148 fix: DEV-3793: LSDV-964: Relative coords for Image regions
  e2e/fragments/AtDetails.js
  e2e/fragments/AtPanels.js
  e2e/fragments/AtTableView.js
  e2e/tests/outliner.test.js
  e2e/tests/regression-tests/image-zoom-position.test.js
  e2e/tests/smoke.test.js
  e2e/tests/table.test.js
  src/components/Entity/Entity.js
  src/components/ImageView/ImageView.js
  src/components/ImageView/LabelOnRegion.js
  src/components/ImageView/SuggestionControls.js
  src/components/RelationsOverlay/BoundingBox.js
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
  src/core/Helpers.ts
  src/mixins/DrawingTool.js
  src/mixins/HighlightMixin.js
  src/mixins/KonvaRegion.js
  src/mixins/LabelMixin.js
  src/mixins/Regions.js
  src/mixins/Tool.js
  src/regions/BrushRegion.js
  src/regions/EllipseRegion.js
  src/regions/ImageRegion.js
  src/regions/KeyPointRegion.js
  src/regions/PolygonPoint.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/regions/Result.js
  src/stores/Annotation/Annotation.js
  src/tags/control/Choices.js
  src/tags/control/DateTime.js
  src/tags/control/List.js
  src/tags/control/Number.js
  src/tags/control/Ranker.js
  src/tags/control/Rating.js
  src/tags/control/Rectangle.js
  src/tags/control/TextArea/TextArea.js
  src/tags/object/Audio.js
  src/tags/object/AudioNext/model.js
  src/tags/object/AudioUltra/model.js
  src/tags/object/Base.js
  src/tags/object/Image/Image.js
  src/tags/object/Image/ImageSelection.js
  src/tags/object/Paragraphs/Model.js
  src/tags/object/TimeSeries.js
  src/tags/object/TimeSeries/Channel.js
  src/tags/object/TimeSeries/helpers.js
  src/tags/object/Video/VideoRegions.js
  src/tags/visual/Dialog.js
  src/tools/Brush.js
  src/tools/Erase.js
  src/tools/KeyPoint.js
  src/tools/Polygon.js
  src/tools/Selection.js
  src/utils/bboxCoords.js
  src/utils/feature-flags.ts
  src/utils/image.js
  src/utils/utilities.ts
Labels: fix

#1228 feat: LSDV-4659: Add skipDuplicates parameter to TextArea
  e2e/codecept.conf.js
  e2e/fragments/AtSidebar.js
  e2e/fragments/Modals.js
  e2e/plugins/featureFlags.js
  e2e/setup/feature-flags.js
  e2e/tests/ocr.test.js
  e2e/tests/textarea.skip-duplicates.test.js
  src/tags/control/TextArea/TextArea.js
  src/utils/feature-flags.ts
Labels: feat, breaking

#1226 fix: LSDV-4706: Video timeline segmentation plays correctly without micro stuttering issues
  src/lib/AudioUltra/Controls/Player.ts
Labels: fix, breaking

#1221 fix: LSDV-4585: Show nested Collapse correctly
  e2e/tests/visual-tags.test.js
  src/tags/visual/Collapse.js
Labels: fix, breaking

#1224 feat: LSDV-4701: Audio v3 webaudio alternative decoder option
  e2e/tests/audio/audio-webaudio-decoder.test.js
  src/lib/AudioUltra/Media/AudioDecoder.ts
  src/lib/AudioUltra/Media/AudioDecoderPool.ts
  src/lib/AudioUltra/Media/BaseAudioDecoder.ts
  src/lib/AudioUltra/Media/MediaLoader.ts
  src/lib/AudioUltra/Media/WaveformAudio.ts
  src/lib/AudioUltra/Media/WebAudioDecoder.ts
  src/lib/AudioUltra/Waveform.ts
  src/tags/object/AudioUltra/model.js
  src/tags/object/AudioUltra/view.tsx
  src/utils/feature-flags.ts
Labels: feat, breaking

#1232 fix: LSDV-4701: Removing feature flag from base file
  src/utils/feature-flags.ts
Labels: fix, breaking

#1231 fix: LSDV-4682: Fix regions shifting in MIG scenario
  e2e/.eslintrc.js
  e2e/tests/image-list.test.js
  src/mixins/Regions.js
Labels: fix, breaking

#1230 fix: LSDV-4676: Region corruption MIG
  e2e/codecept.conf.js
  e2e/fragments/LabelStudio.js
  e2e/helpers/Assertion.js
  e2e/tests/image-list.test.js
  src/components/ImageView/Image.js
  src/components/ImageView/ImageView.js
  src/regions/BrushRegion.js
  src/regions/EllipseRegion.js
  src/regions/KeyPointRegion.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/stores/Annotation/Annotation.js
  src/tags/object/Image/Image.js
Labels: fix, breaking

#1235 docs: LSDV-4707: Remove Repeater from docs
  src/tags/visual/Repeater.js
Labels: breaking, docs

#1233 fix: LSDV-4715: Start, end and offset of paragraph selection should not include empty or newline
  e2e/tests/paragraphs-filter.test.js
  src/tags/object/Paragraphs/Paragraphs.js
Labels: fix, breaking

#1223 fix: LSDV-4649: Regrouping regions after switching annotations
  e2e/codecept.conf.js
  e2e/fragments/AtOutliner.js
  e2e/fragments/AtTopbar.js
  e2e/plugins/errorsCollector.js
  e2e/plugins/featureFlags.js
  e2e/plugins/stepLogsModifier.js
  e2e/tests/audio/audio-controls.test.js
  e2e/tests/image.zoom-rotate.test.js
  e2e/tests/regression-tests/brush-relations.test.js
  e2e/tests/regression-tests/image.regions-select.test.js
  e2e/tests/regression-tests/outliner-regions-dnd.test.js
  e2e/tests/regression-tests/richtext.test.js
  e2e/tests/timeseries.test.js
  e2e/tests/unfinished-polygons.test.js
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/tags/object/Paragraphs/Paragraphs.js
Labels: fix, breaking

#1225 fix: LSDV-4662: Use empty range GET requests instead of HEAD to avoid CORS issue on video presigned urls
  src/components/VideoCanvas/VirtualVideo.tsx
Labels: fix, breaking

#1234 fix: LSDV-4593: CORS error requesting audio
  src/lib/AudioUltra/Media/MediaLoader.ts
Labels: fix, breaking

#1240 fix: LSDV-4752: Support relations in MIG scenario
  package.json
  src/components/RelationsOverlay/RelationsOverlay.js
  src/stores/RelationStore.js
  yarn.lock
Labels: fix, breaking

#1256 ci: Number of tests is increasing, need more time
  .github/workflows/e2e_tests.yml
Labels: ci

#1258 fix: LSDV-4740: Video Rectangles are displaying while drawing
  src/tags/object/Video/VideoRegions.js
Labels: fix, breaking

#1242 docs: LSDV-4754: Update Audio documentation to point to v3
  src/tags/control/Choices.js
  src/tags/control/Labels/Labels.js
  src/tags/control/MagicWand.js
  src/tags/object/Audio.js
  src/tags/object/AudioNext/model.js
  src/tags/object/AudioUltra/model.js
  src/tags/object/Paragraphs/Paragraphs.js
Labels: docs

#1254 fix: LSDV-4774: Drawing on the hidden image in MIG scenario
  src/components/ImageView/ImageView.js
  src/mixins/DrawingTool.js
  src/tools/Brush.js
Labels: fix, breaking

#1259 fix: LSDV-4801: Better file type playable detection for video
  e2e/tests/helpers.js
  jest.config.js
  jest.setup.js
  package.json
  src/components/VideoCanvas/VirtualVideo.tsx
  src/components/VideoCanvas/__tests__/VirtualVideo.test.tsx
  src/lib/AudioUltra/Media/MediaLoader.ts
  yarn.lock
Labels: fix, breaking

#1257 fix: LSDV-4747: Selecting the end character on a Paragraph phrase to the very start of other phrases only includes the first phrase selection
  e2e/codecept.conf.js
  e2e/tests/paragraphs-filter.test.js
  src/tags/object/Paragraphs/Paragraphs.js
  src/tags/object/Paragraphs/Phrases.js
  src/utils/html.js
Labels: fix, breaking

#1270 fix: LSDV-4811: Impossible to select and drag a hidden region
  src/tags/object/Video/VideoRegions.js
Labels: fix

#1268 fix: LSDV-4708: Scroll page to canvas only if needed
  src/mixins/KonvaRegion.js
  src/stores/RegionStore.js
Labels: fix

#1276 ci: SRE-471: Publish tags from LSF repo to LS
  .github/workflows/release-set-version.yml
Labels: ci

#1280 test: Fix MIG tests
  e2e/fragments/AtImageView.js
  e2e/tests/image-list.test.js
Labels: test

#1277 docs: LSDV-4874: Update audio documentation to outline splitchannels usage
  src/tags/object/AudioUltra/model.js
Labels: docs

#1279 feat: LSDV-3025-1: LSDV-3025-2: Create reusable filter and filter row component
  src/assets/icons/delete.svg
  src/assets/icons/filter.svg
  src/assets/icons/index.tsx
  src/common/Icon/Icon.js
  src/common/Icon/Icon.styl
  src/components/Filter/Filter.styl
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterDropdown.tsx
  src/components/Filter/FilterInput.tsx
  src/components/Filter/FilterInterfaces.tsx
  src/components/Filter/FilterRow.styl
  src/components/Filter/FilterRow.tsx
  src/components/Filter/types/Boolean.js
  src/components/Filter/types/Common.js
  src/components/Filter/types/Number.js
  src/components/Filter/types/String.js
  src/components/Filter/types/index.js
  src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
Labels: feat

#1282 feat: LSDV-3025-5: Create the filtering functionality in the new filter component
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterDropdown.tsx
  src/components/Filter/FilterInterfaces.tsx
  src/components/Filter/FilterRow.tsx
  src/components/Filter/__tests__/filter-utils.test.tsx
  src/components/Filter/filter-util.ts
  src/components/SidePanels/OutlinerPanel/ViewControls.tsx
Labels: feat
