Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-06, with the labels that each got.

#1424 fix: LSDV-5214: Multi-word labels containing spaces in regions list are broken down into multiple rows on every space character
  src/components/SidePanels/OutlinerPanel/TreeView.styl
Labels: fix

#1427 fix: LSDV-5158: Hide prediction delete button as it doesn't actually allow prediction deletions at this time
  src/components/AnnotationsCarousel/AnnotationButton.tsx
Labels: fix

#1420 feat: LSDV-5121: User Setting Improvements
  src/assets/icons/close.svg
  src/assets/icons/index.tsx
  src/common/Toggle/Toggle.styl
  src/components/Settings/Settings.js
  src/components/Settings/Settings.styl
  src/core/settings/editorsettings.js
Labels: feat

#1429 chore: 1.8.0 cherrypick 2023 06 01
  src/assets/icons/close.svg
  src/assets/icons/index.tsx
  src/common/Toggle/Toggle.styl
  src/components/AnnotationsCarousel/AnnotationButton.tsx
  src/components/Ranker/Ranker.tsx
  src/components/Settings/Settings.js
  src/components/Settings/Settings.styl
  src/components/SidePanels/OutlinerPanel/TreeView.styl
  src/core/settings/editorsettings.js
  src/tags/control/Ranker.js
  src/tags/control/__tests__/Ranker.test.ts
  src/tags/object/List.js
Labels: chore

#1432 fix: LSDV-5235: Postpone should not require FF to operate
  src/components/BottomBar/CurrentTask.js
Labels: fix

#1434 fix: LSDV-5235: Use alternate check for postpone based on presence of interfaces instead of FF
  src/components/TopBar/CurrentTask.js
Labels: fix

#1430 fix: LSDV-E-135: Dependabot updates
  e2e/package.json
  e2e/yarn.lock
  yarn.lock
Labels: fix

#1419 fix: LSDV-3861: XSS in error messages
  src/utils/messages.js
Labels: fix

#1345 fix: LSDV-4968: Fix remaining transformer of selected region outside of lifespan
  src/tags/object/Video/VideoRegions.js
  tests/functional/data/video_segmentation/regions.ts
  tests/functional/package.json
  tests/functional/specs/video_segmentation/regions.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1440 fix: LSDV-5089: Manual security updates
  e2e/package.json
  e2e/yarn.lock
  package.json
  yarn.lock
Labels: fix

#1443 chore: Bump loader-utils from 2.0.3 to 2.0.4
  package.json
  yarn.lock
Labels: chore

#1379 fix: LSDV-5001: Skip comments panel focus
  src/components/App/App.js
  src/components/BottomBar/Controls.js
  src/components/Comments/CommentForm.tsx
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
  src/components/SidePanels/TabPanels/__tests__/utils.test.tsx
  src/components/SidePanels/TabPanels/types.ts
  src/components/SidePanels/TabPanels/utils.ts
  src/stores/AppStore.js
Labels: fix

#1329 chore: LSDV-4983: Consistent feature flags
  src/core/feature-flags/flags.json
  src/core/feature-flags/index.ts
Labels: chore

#1448 fix: LSDV-5001: Skip comments panel focus
  src/components/App/App.js
  src/components/BottomBar/Controls.js
  src/components/Comments/CommentForm.tsx
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
  src/components/SidePanels/TabPanels/__tests__/utils.test.tsx
  src/components/SidePanels/TabPanels/types.ts
  src/components/SidePanels/TabPanels/utils.ts
  src/stores/AppStore.js
Labels: fix

#1447 fix: LSDV-5262: Save draft on postpone
  src/stores/Annotation/Annotation.js
  src/stores/AppStore.js
Labels: fix

#1425 fix: LSDV-4673: Fix drawing with Rect3Point tool in relative coords
  src/components/ImageView/Image.js
  src/mixins/DrawingTool.js
  src/mixins/Regions.js
  src/regions/EllipseRegion.js
  src/regions/KeyPointRegion.js
  src/regions/PolygonPoint.js
  src/regions/PolygonRegion.js
  src/regions/RectRegion.js
  src/tags/control/Rectangle.js
  src/tags/object/Image/Image.js
  src/tags/object/Image/ImageSelection.js
  src/tools/Rect.js
  src/utils/feature-flags.ts
  tests/functional/data/image_segmentation/tools/rect3point.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/image_segmentation/tools/rect3point.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1450 fix: LSDV-1666: Fix lock option isn't locking audio regions
  src/lib/AudioUltra/Regions/Segment.ts
  src/regions/AudioRegion/AudioRegionModel.js
  src/regions/AudioRegion/AudioUltraRegionModel.js
Labels: fix

#1458 fix: LSDV-5259: Duplication of annotations can only happen if creation is allowed.
  src/components/AnnotationsCarousel/AnnotationButton.tsx
Labels: fix

#1457 fix: LSDV-5259: Duplication of annotations can only happen if creation is allowed.
  src/components/AnnotationsCarousel/AnnotationButton.tsx
Labels: fix

#1454 fix: LSDV-5260: Selected region can not be moved / resized when it's under another region
  e2e/tests/audio/audio-regions.test.js
  src/lib/AudioUltra/Regions/Regions.ts
  src/lib/AudioUltra/Regions/Segment.ts
  src/regions/AudioRegion/AudioUltraRegionModel.js
Labels: fix

#1462 ci: SRE-541: Dynamic GH org name
  .github/workflows/sync-pr-ls.yml
  .github/workflows/sync-pr-lse.yml
Labels: ci

#1464 ci: Fix syntax
  .github/workflows/sync-pr-ls.yml
  .github/workflows/sync-pr-lse.yml
Labels: ci

#1381 feat: LSDV-4654: Allow per-image classification
  scripts/create-docs.js
  src/components/ImageView/ImageView.js
  src/core/DataValidator/ConfigValidator.js
  src/mixins/PerItem.js
  src/mixins/PerRegion.js
  src/mixins/Required.js
  src/stores/Annotation/Annotation.js
  src/stores/Annotation/store.js
  src/tags/TagBase.js
  src/tags/control/Base.js
  src/tags/control/BrushLabels.js
  src/tags/control/Choice.js
  src/tags/control/Choices.js
  src/tags/control/ClassificationBase.js
  src/tags/control/DateTime.js
  src/tags/control/EllipseLabels.js
  src/tags/control/KeyPointLabels.js
  src/tags/control/Labels/Labels.js
  src/tags/control/Number.js
  src/tags/control/Pairwise.js
  src/tags/control/PolygonLabels.js
  src/tags/control/Rating.js
  src/tags/control/RectangleLabels.js
  src/tags/control/Taxonomy/Taxonomy.js
  src/tags/control/TextArea/TextArea.js
  src/tags/control/TimeSeriesLabels.js
  src/tags/control/VideoRectangle.js
  src/tags/object/AudioNext/model.js
  src/tags/object/AudioUltra/model.js
  src/tags/object/Base.js
  src/tags/object/Image/Image.js
  src/tags/object/Image/ImageEntityMixin.js
  src/tags/object/MultiItemObjectBase.js
  src/tags/object/Paragraphs/model.js
  src/tags/object/RichText/model.js
  src/tags/object/TimeSeries.js
  src/tags/object/Video/Video.js
  tests/functional/data/control_tags/per-item.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/control_tags/classification/per-item.cy.ts
  tests/functional/yarn.lock
Labels: feat

#1372 fix: LSDV-5066: Filter row validation to set filter just if value is added
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterDropdown.tsx
  src/components/Filter/FilterRow.tsx
  src/components/Filter/filter-util.ts
  tests/functional/specs/outliner/filter.cy.ts
Labels: fix

#1331 fix: LSDV-4930: Fix selection tool
  e2e/setup/feature-flags.js
  e2e/tests/helpers.js
  src/components/ImageView/ImageView.js
  src/mixins/AreaMixin.js
  src/mixins/DrawingTool.js
  src/tools/Selection.js
  src/utils/feature-flags.ts
  tests/functional/data/image_segmentstion/tools/selection-tool.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/core/feature_flags.cy.ts
  tests/functional/specs/image_segmentation/tools/selection-tool.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1471 ci: SRE-541: Local workflow call
  .github/workflows/cicd_pipeline.yml
  .github/workflows/release-set-version.yml
Labels: ci

#1365 fix: LSDV-4988: Fix No Label for Dynamic Labels
  src/stores/Annotation/Annotation.js
  src/utils/feature-flags.ts
Labels: fix

#1472 fix: LSDV-5250: Hotkey for creating relations not working
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
  src/stores/AppStore.js
  tests/functional/package.json
  tests/functional/specs/relations/image_rectangle_regions.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1469 feat: LSDV-5296: Scroll container max height
  src/tags/object/Paragraphs/HtxParagraphs.js
  src/tags/object/Paragraphs/Paragraphs.module.scss
  src/tags/object/Paragraphs/model.js
  src/utils/feature-flags.ts
Labels: feat

#1474 fix: LSDV-5314: Persist collapse panel state
  src/components/SidePanels/TabPanels/SideTabsPanels.tsx
  src/components/SidePanels/TabPanels/__tests__/utils.test.tsx
  src/components/SidePanels/TabPanels/utils.ts
Labels: fix

#1484 fix: LSDV-5296: Disconnect observer
  src/tags/object/Paragraphs/HtxParagraphs.js
Labels: fix

#1470 fix: LSDV-4853: Add warning message when user selects more choices than maxUsages
  src/tags/control/Choices.js
  src/tags/control/Taxonomy/Taxonomy.js
  tests/functional/data/control_tags/taxonomy.ts
  tests/functional/specs/control_tags/taxonomy.cy.ts
Labels: fix

#1478 fix: LSDV-5316: Fix Ctrl/Cmd+X in Config Editor
  src/hooks/useRegionsCopyPaste.ts
Labels: fix
