Repository HumanSignal/label-studio-frontend, pull requests merged in 2023-09, with the labels that each got.

#1523 fix: LSDV-5248: BBoxes optimizations
  e2e/fragments/AtImageView.js
  e2e/fragments/AtOutliner.js
  e2e/helpers/MouseActions.js
  e2e/setup/feature-flags.js
  e2e/tests/ocr.test.js
  src/components/ImageView/ImageView.js
  src/mixins/KonvaRegion.js
  src/regions/AliveRegion.tsx
  src/regions/BrushRegion.js
  src/regions/KeyPointRegion.js
  src/utils/feature-flags.ts
  tests/functional/data/image_segmentation/layers.ts
  tests/functional/data/image_segmentation/tools/selection-tool.ts
  tests/functional/feature-flags.ts
  tests/functional/specs/image_segmentation/layers.cy.ts
  tests/functional/specs/image_segmentation/tools/selection-tool.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1545 fix: LSDV-5487: Keep the labeling interface settings after change page
  src/stores/SettingsStore.js
Labels: fix

#1535 fix: LSDV-5526: Fix duplication of classifications in LLM scenario
  src/regions/Area.js
  src/stores/Annotation/Annotation.js
  tests/functional/data/lmm/accept_suggestions.ts
  tests/functional/feature-flags.ts
  tests/functional/package.json
  tests/functional/specs/llm/accept_suggestions.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1553 fix: LEAP-36: Taxonomy alias + other important fixes
  src/components/NewTaxonomy/NewTaxonomy.tsx
  src/tags/control/Taxonomy/Taxonomy.js
  tests/functional/data/control_tags/taxonomy.ts
  tests/functional/package.json
  tests/functional/specs/control_tags/taxonomy.cy.ts
  tests/functional/tsconfig.json
  tests/functional/yarn.lock
Labels: fix

#1541 feat: OPTIC-3: Enable users to submit and pause their lead time by returning to the dm list
  src/components/BottomBar/Controls.js
  src/components/BottomBar/Controls.styl
  src/utils/feature-flags.ts
Labels: feat

#1552 feat: OPTIC-2: Save draft on leave
  src/stores/Annotation/Annotation.js
  src/stores/AppStore.js
Labels: feat

#1563 feat: LEAP-187: Skip Video to region start on select
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/regions/VideoRegion.js
  src/utils/feature-flags.ts
Labels: feat

#1559 fix: LSDV-5547: Support HTML in Instructions modal
  src/components/InstructionsModal/InstructionsModal.tsx
  src/components/InstructionsModal/__tests__/InstructionsModal.test.tsx
Labels: fix

#1539 feat: LSDV-5518: Add snap prop to snap polygon to image pixels
  src/components/ImageTransformer/ImageTransformer.js
  src/components/ImageView/Image.js
  src/components/ImageView/ImageView.js
  src/regions/KeyPointRegion.js
  src/regions/PolygonPoint.js
  src/regions/PolygonRegion.js
  src/tags/control/Base.js
  src/tags/control/KeyPoint.js
  src/tags/control/KeyPointLabels.js
  src/tags/control/Polygon.js
  src/tags/control/PolygonLabels.js
  src/tags/object/Image/Image.js
  src/tools/KeyPoint.js
  src/tools/Polygon.js
  src/utils/feature-flags.ts
Labels: feat

#298 chore: add devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: title needs formatting

#1562 fix: OPTIC-109: Blank draft should not be created when an annotation is submitted
  src/components/BottomBar/Controls.js
  src/stores/Annotation/Annotation.js
  src/stores/AppStore.js
  tests/functional/package.json
  tests/functional/yarn.lock
Labels: fix

#1561 fix: LSDV-5560: Fix plus and minus hotkeys
  src/core/Hotkey.ts
  tests/functional/data/image_segmentation/tools/zoom.ts
  tests/functional/package.json
  tests/functional/specs/image_segmentation/tools/zoom.cy.ts
  tests/functional/yarn.lock
Labels: fix

#1573 fix: OPTIC-133: Blank draft submitted with annotation when using hotkey submit
  src/stores/AppStore.js
Labels: fix
