Repository HumanSignal/label-studio-frontend, pull requests merged in 2024-02, with the labels that each got.

#1689 fix: LEAP-640: Don't save empty draft on View All
  src/components/TopBar/Actions.js
  src/components/TopBar/TopBar.js
  src/stores/Annotation/store.js
Labels: fix

#1687 fix: OPTIC-411: [lsp] Fix Follow Redirects improperly handles URLs in the url.parse() function
  e2e/package.json
  e2e/yarn.lock
  package.json
  src/components/NewTaxonomy/NewTaxonomy.tsx
  yarn.lock
Labels: fix

#1682 docs: LEAP-615: Mention spaces saving for Text tag
  src/tags/object/Text.js
Labels: docs

#1640 fix: LEAP-443: Select only one annotation on init
  LSF.init.md
  src/Component.js
  src/LabelStudio.tsx
  src/common/Pagination/Pagination.tsx
  src/components/AnnotationTabs/AnnotationTabs.js
  src/components/Annotations/Annotations.js
  src/components/AnnotationsCarousel/AnnotationsCarousel.tsx
  src/components/AnnotationsCarousel/__tests__/sampleData.js
  src/components/App/App.js
  src/components/HtxTextBox/HtxTextBox.js
  src/components/ImageView/ImageView.js
  src/components/Panel/Panel.js
  src/components/Predictions/Predictions.js
  src/components/SidebarTabs/SidebarTabs.js
  src/configureStore.js
  src/mixins/AnnotationMixin.js
  src/registerPanels.js
  src/stores/Annotation/Annotation.js
  src/stores/Annotation/store.js
  src/stores/AppStore.js
  src/stores/RelationStore.js
  src/tags/control/__tests__/Ranker.test.ts
  src/tools/Manager.js
  src/utils/feature-flags.ts
  src/utils/utilities.ts
Labels: fix, Confirmed

#1705 fix: LEAP-724: Fix Textarea required + skipDuplicates
  e2e/tests/ocr.test.js
  e2e/tests/textarea.skip-duplicates.test.js
  src/regions/TextAreaRegion.js
  src/tags/control/TextArea/TextArea.js
  src/tags/control/TextArea/TextAreaRegionView.js
  src/utils/feature-flags.ts
Labels: fix, Confirmed

#1706 fix: LEAP-740: Don't use destroy = null
  e2e/tests/helpers.js
  e2e/tests/image.transformer.test.js
  e2e/tests/maxUsage.test.js
  e2e/tests/regression-tests/brush-relations.test.js
  e2e/tests/regression-tests/image-width.test.js
  src/LabelStudio.tsx
Labels: fix, Confirmed
