Repository HumanSignal/label-studio-frontend, pull requests merged in 2024-01, with the labels that each got.

#1651 fix: LEAP-444: Implement HTML sanitization in LSF
  src/components/App/App.js
  src/components/ErrorMessage/ErrorMessage.js
  src/components/InstructionsModal/InstructionsModal.tsx
  src/tags/control/Choice.js
  src/tags/control/Label.js
  src/tags/visual/Style.js
  src/utils/__tests__/html.test.ts
  src/utils/feature-flags.ts
  src/utils/html.js
Labels: fix, Confirmed

#1652 fix: OPTIC-354: Comment draft preserved between annotations
  src/components/Comments/CommentForm.tsx
  src/components/Comments/Comments.tsx
  src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
  src/stores/Comment/CommentStore.js
Labels: fix, Confirmed

#1653 fix: LEAP-248: Fix app crashing by hotkeys
  src/core/Hotkey.ts
  tests/functional/data/core/hotkeys.ts
  tests/functional/specs/core/hotkeys.cy.ts
Labels: fix, Confirmed

#1657 fix: LEAP-344: View all annotation tab is not loading
  src/components/App/Grid.js
Labels: fix, Confirmed

#1636 feat: LEAP-355: Make relations work with TimeTraveler
  src/components/RelationsOverlay/RelationsOverlay.js
  src/components/SidePanels/DetailsPanel/Relations.styl
  src/components/SidePanels/DetailsPanel/Relations.tsx
  src/stores/Annotation/Annotation.js
  src/stores/RelationStore.js
  src/tags/control/Relation.js
  src/tags/control/Relations.js
  tests/functional/data/relations/basic.ts
  tests/functional/package.json
  tests/functional/specs/control_tags/taxonomy.cy.ts
  tests/functional/specs/relations/basic.cy.ts
  tests/functional/specs/video_segmentation/regions.cy.ts
  tests/functional/yarn.lock
Labels: feat, Confirmed

#1637 feat: OPTIC-107: Draft saving on view all
  src/components/TopBar/Actions.js
  src/components/TopBar/TopBar.js
  src/core/TimeTraveller.js
  src/stores/Annotation/Annotation.js
Labels: feat, Confirmed

#1661 fix: LEAP-515: Fix CommentForm for old UI
  src/components/AnnotationTab/AnnotationTab.js
Labels: fix

#1659 fix: LEAP-439: Add maskData exporting into new MIG serialization approach
  src/regions/BrushRegion.js
  src/utils/canvas.js
  tests/functional/package.json
  tests/functional/specs/image_segmentation/tools/magic-wand.cy.ts
  tests/functional/yarn.lock
Labels: fix, Confirmed

#1665 fix: OPTIC-353: Fix null errors when switching from task detail to settings
  src/LabelStudio.js
  src/regions/VideoRegion.js
Labels: fix, Confirmed

#1666 fix: LEAP-246: Replace overlaping MIG hotkeys
  src/core/Hotkey.ts
  src/core/settings/keymap.json
  src/utils/feature-flags.ts
Labels: fix, Confirmed

#1678 fix: LEAP-580: Display non-string values in Text
  src/tags/object/RichText/model.js
  src/utils/data.js
  tests/functional/specs/object_tags/text.cy.ts
Labels: fix

#1679 chore: Cherry picked OPTIC-353 into release 1.11.0
  src/LabelStudio.js
  src/regions/VideoRegion.js
Labels: chore

#1673 fix: LEAP-509: Optimize regular expression for improved performance
  src/utils/data.js
Labels: fix, Confirmed

#1613 ci: New PR template
  .github/pull_request_template.md
Labels: ci

#1674 fix: LEAP-523: Return region's text to item in a list
  e2e/tests/ner-text.test.js
  src/components/Node/Node.tsx
  src/components/SidePanels/DetailsPanel/RegionDetails.tsx
  src/components/SidePanels/DetailsPanel/RegionItem.tsx
  src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
  src/components/SidePanels/OutlinerPanel/TreeView.styl
Labels: fix, Confirmed

#1667 fix: LEAP-240: Prevent creating region on clicking outside selected one
  src/components/ImageView/ImageView.js
  tests/functional/data/image_segmentation/tools/rect.ts
  tests/functional/specs/image_segmentation/tools/rect.cy.ts
Labels: fix, Confirmed

#1649 fix: LEAP-447: Fix Number tag validation
  src/mixins/PerItem.js
  src/mixins/PerRegion.js
  src/mixins/Required.js
  src/tags/control/ClassificationBase.js
  src/tags/control/DateTime.js
  src/tags/control/Number.js
  tests/functional/data/control_tags/number.ts
  tests/functional/package.json
  tests/functional/specs/control_tags/number.cy.ts
  tests/functional/yarn.lock
Labels: fix, Confirmed

#1686 ci: PLATE-838: Add actions-hub to git ignore
  .gitignore
Labels: ci

#1685 fix: LEAP-148: Fix MagicWand in MIG scenario with image preloading
  src/components/ImageView/Image.js
  src/components/ImageView/ImageView.js
  src/tools/MagicWand.js
  tests/functional/package.json
  tests/functional/specs/relations/basic.cy.ts
  tests/functional/yarn.lock
Labels: fix, Confirmed
